package com.yss.valset.parser.application.service;

import com.yss.cloud.dto.response.PageResult;
import com.yss.valset.parser.application.command.ParseQueueBackfillCommand;
import com.yss.valset.parser.application.command.ParseQueueCompleteCommand;
import com.yss.valset.parser.application.command.ParseQueueFailCommand;
import com.yss.valset.parser.application.command.ParseQueueGenerateCommand;
import com.yss.valset.parser.application.command.ParseQueueQueryCommand;
import com.yss.valset.parser.application.command.ParseQueueRetryCommand;
import com.yss.valset.parser.application.command.ParseQueueSubscribeCommand;
import com.yss.valset.parser.application.dto.ParseQueueViewDTO;
import com.yss.valset.transfer.domain.model.TransferDeliveryRecord;
import com.yss.valset.transfer.domain.model.TransferObject;

import java.util.List;

/**
 * 待解析任务管理服务。
 */
public interface ParseQueueManagementAppService {

    PageResult<ParseQueueViewDTO> pageQueues(ParseQueueQueryCommand query);

    ParseQueueViewDTO getQueue(String queueId);

    ParseQueueViewDTO generateQueue(ParseQueueGenerateCommand command);

    List<ParseQueueViewDTO> backfillQueues(ParseQueueBackfillCommand command);

    ParseQueueViewDTO subscribeQueue(String queueId, ParseQueueSubscribeCommand command);

    ParseQueueViewDTO completeQueue(String queueId, ParseQueueCompleteCommand command);

    ParseQueueViewDTO failQueue(String queueId, ParseQueueFailCommand command);

    ParseQueueViewDTO retryQueue(String queueId, ParseQueueRetryCommand command);

    void ensureAutoGenerated(TransferObject transferObject, TransferDeliveryRecord deliveryRecord);
}
