package com.yss.valset.transfer.domain.model;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Map;

/**
 * 已收取的文件主对象。
 */
public record TransferObject(
        String transferId,
        String sourceId,
        String sourceType,
        String sourceCode,
        String originalName,
        String extension,
        String mimeType,
        Long sizeBytes,
        String fingerprint,
        String sourceRef,
        String mailId,
        String mailFrom,
        String mailTo,
        String mailCc,
        String mailBcc,
        String mailSubject,
        String mailBody,
        String mailProtocol,
        String mailFolder,
        String localTempPath,
        TransferStatus status,
        Instant receivedAt,
        Instant storedAt,
        LocalDate businessDate,
        String businessId,
        LocalDate receiveDate,
        String routeId,
        String errorMessage,
        ProbeResult probeResult,
        Map<String, Object> fileMeta,
        String realStoragePath
) {

    public TransferObject(String transferId,
                          String sourceId,
                          String sourceType,
                          String sourceCode,
                          String originalName,
                          String extension,
                          String mimeType,
                          Long sizeBytes,
                          String fingerprint,
                          String sourceRef,
                          String mailId,
                          String mailFrom,
                          String mailTo,
                          String mailCc,
                          String mailBcc,
                          String mailSubject,
                          String mailBody,
                          String mailProtocol,
                          String mailFolder,
                          String localTempPath,
                          TransferStatus status,
                          Instant receivedAt,
                          Instant storedAt,
                          String routeId,
                          String errorMessage,
                          ProbeResult probeResult,
                          Map<String, Object> fileMeta) {
        this(transferId, sourceId, sourceType, sourceCode, originalName, extension, mimeType, sizeBytes, fingerprint, sourceRef,
                mailId, mailFrom, mailTo, mailCc, mailBcc, mailSubject, mailBody, mailProtocol, mailFolder, localTempPath,
                status, receivedAt, storedAt, null, null, null, routeId, errorMessage, probeResult, fileMeta, null);
    }

    public TransferObject withLocalTempPath(String localTempPath) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withRealStoragePath(String realStoragePath) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withBusinessDate(LocalDate businessDate) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withBusinessId(String businessId) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withReceiveDate(LocalDate receiveDate) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withBusinessFields(LocalDate businessDate, String businessId, LocalDate receiveDate) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withRouteId(String routeId) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withStatus(TransferStatus status, String errorMessage) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withProbeResult(ProbeResult probeResult) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withFileMeta(Map<String, Object> fileMeta) {
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailId,
                mailFrom,
                mailTo,
                mailCc,
                mailBcc,
                mailSubject,
                mailBody,
                mailProtocol,
                mailFolder,
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }

    public TransferObject withMailInfo(TransferMailInfo mailInfo) {
        if (mailInfo == null) {
            return this;
        }
        return new TransferObject(
                transferId,
                sourceId,
                sourceType,
                sourceCode,
                originalName,
                extension,
                mimeType,
                sizeBytes,
                fingerprint,
                sourceRef,
                mailInfo.mailId(),
                mailInfo.mailFrom(),
                mailInfo.mailTo(),
                mailInfo.mailCc(),
                mailInfo.mailBcc(),
                mailInfo.mailSubject(),
                mailInfo.mailBody(),
                mailInfo.mailProtocol(),
                mailInfo.mailFolder(),
                localTempPath,
                status,
                receivedAt,
                storedAt,
                businessDate,
                businessId,
                receiveDate,
                routeId,
                errorMessage,
                probeResult,
                fileMeta,
                realStoragePath
        );
    }
}
