import type { YTablePagination } from "@yss-ui/components";

export interface SourcePage {
  loading: boolean;
  rows: any[];
  tableData: any[];
  total: number;
  pageSize: number;
  pagination: YTablePagination;
  query: {
    sourceType: string;
    sourceCode: string;
    sourceName: string;
    enabled: string;
    limit: number;
  };
  sourceTypeOptions: Array<{ label: string; value: string }>;
  templateNamePreview: string;
  templateDescription: string;
  templateVersion: string;
  templateMode: 0 | 1 | 2;
  templateReadPretty: boolean;
  templateSchema: any | null;
  templateInitialValues: Record<string, any>;
  templateValues: Record<string, any>;
  templateScope: Record<string, any>;
  templateLoading: boolean;
  uploadVisible: boolean;
  uploadSubmitting: boolean;
  uploadSourceRow: any | null;
  uploadFiles: File[];
  uploadEndpoint: string;
  isUploadAllowed: (row?: any | null) => boolean;
  isUploadMultipleAllowed: () => boolean;
  openUploadDialog: (row: any) => void;
  closeUploadDialog: () => void;
  handleUploadInputChange: (event: Event) => void;
  removeUploadFile: (index: number) => void;
  submitUpload: () => Promise<void> | void;
  enabledUpdatingIds: Record<string, boolean>;
  templateDetailOptions: Record<string, any>;
  templateGridDefaults: Record<string, any>;
  setTemplateFormRef: (instance: any) => void;
  isEnabledUpdating: (sourceId?: string) => boolean;
  hasEnabledRoutes: (row?: any | null) => boolean;
  isIngestRunning: (row?: any | null) => boolean;
  isIngestBusy: (row?: any | null) => boolean;
  formatIngestStatus: (value?: string) => string;
  toggleEnabled: (row: any, checked: boolean) => Promise<void>;
  enabledCount: number;
  templateBoundCount: number;
  sourceTypeCount: number;
  formVisible: boolean;
  formMode: "create" | "edit";
  editingRow: any | null;
  formState: {
    sourceId?: string;
    sourceCode: string;
    sourceName: string;
    sourceType: string;
    enabled: boolean;
    connectionConfigText: string;
    sourceMetaText: string;
  };
  detailVisible: boolean;
  selectedRow: any | null;
  checkpointRows: any[];
  checkpointItemRows: any[];
  checkpointLoading: boolean;
  formSubmitting: boolean;
  openCreateDialog: () => void;
  openEditDialog: (row: any) => void;
  openDetailDrawer: (row: any) => void;
  confirmDelete: (row: any) => void;
  runQuery: () => void;
  resetQuery: () => void;
  submitForm: () => Promise<void> | void;
  canUploadSource: (row?: any | null) => boolean;
  closeForm: () => void;
  closeDetail: () => void;
  formatEnabled: (value: boolean | undefined) => string;
  handlePageChange: (params: { current: number; pageSize: number }) => void;
}
