import type { YTablePagination } from "@yss-ui/components";

export interface SourcePage {
  loading: boolean;
  rows: any[];
  tableData: any[];
  total: number;
  pageSize: number;
  pagination: YTablePagination;
  query: {
    sourceType: string;
    sourceCode: string;
    sourceName: string;
    enabled: string;
    limit: number;
  };
  sourceTypeOptions: Array<{ label: string; value: string }>;
  templateNamePreview: string;
  templateDescription: string;
  templateVersion: string;
  templateMode: 0 | 1 | 2;
  templateReadPretty: boolean;
  templateSchema: any | null;
  templateInitialValues: Record<string, any>;
  templateValues: Record<string, any>;
  templateScope: Record<string, any>;
  templateLoading: boolean;
  enabledUpdatingIds: Record<string, boolean>;
  triggeringIds: Record<string, boolean>;
  templateDetailOptions: Record<string, any>;
  templateGridDefaults: Record<string, any>;
  setTemplateFormRef: (instance: any) => void;
  isEnabledUpdating: (sourceId?: string) => boolean;
  isIngestRunning: (row?: any | null) => boolean;
  isIngestBusy: (row?: any | null) => boolean;
  isTriggering: (row?: any | null) => boolean;
  formatIngestStatus: (value?: string) => string;
  triggerSource: (row: any) => Promise<void> | void;
  stopSource: (row: any) => Promise<void> | void;
  toggleEnabled: (row: any, checked: boolean) => Promise<void>;
  enabledCount: number;
  templateBoundCount: number;
  sourceTypeCount: number;
  formVisible: boolean;
  formMode: "create" | "edit";
  formState: {
    sourceId?: string;
    sourceCode: string;
    sourceName: string;
  sourceType: string;
  enabled: boolean;
  pollCron: string;
  connectionConfigText: string;
  sourceMetaText: string;
};
  detailVisible: boolean;
  selectedRow: any | null;
  checkpointRows: any[];
  checkpointItemRows: any[];
  checkpointLoading: boolean;
  formSubmitting: boolean;
  openCreateDialog: () => void;
  openEditDialog: (row: any) => void;
  openDetailDrawer: (row: any) => void;
  confirmDelete: (row: any) => void;
  runQuery: () => void;
  resetQuery: () => void;
  submitForm: () => Promise<void> | void;
  closeForm: () => void;
  closeDetail: () => void;
  formatEnabled: (value: boolean | undefined) => string;
  handlePageChange: (params: { current: number; pageSize: number }) => void;
}
