-- ----------------------------
-- Table structure for BATCH_JOB_EXECUTION
-- ----------------------------
CREATE TABLE "BATCH_JOB_EXECUTION" (
  "JOB_EXECUTION_ID" NUMBER(20) NOT NULL,
  "VERSION" NUMBER(20),
  "JOB_INSTANCE_ID" NUMBER(20) NOT NULL,
  "CREATE_TIME" DATE NOT NULL,
  "START_TIME" DATE,
  "END_TIME" DATE,
  "STATUS" VARCHAR2(10),
  "EXIT_CODE" CLOB,
  "EXIT_MESSAGE" CLOB,
  "LAST_UPDATED" DATE,
  "JOB_CONFIGURATION_LOCATION" CLOB
)
;

-- ----------------------------
-- Table structure for BATCH_JOB_EXECUTION_CONTEXT
-- ----------------------------
CREATE TABLE "BATCH_JOB_EXECUTION_CONTEXT" (
  "JOB_EXECUTION_ID" NUMBER(20) NOT NULL,
  "SHORT_CONTEXT" CLOB NOT NULL,
  "SERIALIZED_CONTEXT" CLOB
)
;

-- ----------------------------
-- Table structure for BATCH_JOB_EXECUTION_PARAMS
-- ----------------------------
CREATE TABLE "BATCH_JOB_EXECUTION_PARAMS" (
  "JOB_EXECUTION_ID" NUMBER(20) NOT NULL,
  "TYPE_CD" VARCHAR2(6) NOT NULL,
  "KEY_NAME" VARCHAR2(100) NOT NULL,
  "STRING_VAL" CLOB,
  "DATE_VAL" DATE,
  "LONG_VAL" NUMBER(20),
  "DOUBLE_VAL" NUMBER,
  "IDENTIFYING" NCHAR(1) NOT NULL
)
;

-- ----------------------------
-- Table structure for BATCH_JOB_EXECUTION_SEQ
-- ----------------------------
CREATE TABLE "BATCH_JOB_EXECUTION_SEQ" (
  "ID" NUMBER(20) NOT NULL,
  "UNIQUE_KEY" NCHAR(1) NOT NULL
)
;

-- ----------------------------
-- Table structure for BATCH_JOB_INSTANCE
-- ----------------------------
CREATE TABLE "BATCH_JOB_INSTANCE" (
  "JOB_INSTANCE_ID" NUMBER(20) NOT NULL,
  "VERSION" NUMBER(20),
  "JOB_NAME" VARCHAR2(100) NOT NULL,
  "JOB_KEY" VARCHAR2(32) NOT NULL
)
;

-- ----------------------------
-- Table structure for BATCH_JOB_SEQ
-- ----------------------------
CREATE TABLE "BATCH_JOB_SEQ" (
  "ID" NUMBER(20) NOT NULL,
  "UNIQUE_KEY" NCHAR(1) NOT NULL
)
;

-- ----------------------------
-- Table structure for BATCH_STEP_EXECUTION
-- ----------------------------
CREATE TABLE "BATCH_STEP_EXECUTION" (
  "STEP_EXECUTION_ID" NUMBER(20) NOT NULL,
  "VERSION" NUMBER(20) NOT NULL,
  "STEP_NAME" VARCHAR2(100) NOT NULL,
  "JOB_EXECUTION_ID" NUMBER(20) NOT NULL,
  "START_TIME" DATE NOT NULL,
  "END_TIME" DATE,
  "STATUS" VARCHAR2(10),
  "COMMIT_COUNT" NUMBER(20),
  "READ_COUNT" NUMBER(20),
  "FILTER_COUNT" NUMBER(20),
  "WRITE_COUNT" NUMBER(20),
  "READ_SKIP_COUNT" NUMBER(20),
  "WRITE_SKIP_COUNT" NUMBER(20),
  "PROCESS_SKIP_COUNT" NUMBER(20),
  "ROLLBACK_COUNT" NUMBER(20),
  "EXIT_CODE" CLOB,
  "EXIT_MESSAGE" CLOB,
  "LAST_UPDATED" DATE
)
;

-- ----------------------------
-- Table structure for BATCH_STEP_EXECUTION_CONTEXT
-- ----------------------------
CREATE TABLE "BATCH_STEP_EXECUTION_CONTEXT" (
  "STEP_EXECUTION_ID" NUMBER(20) NOT NULL,
  "SHORT_CONTEXT" CLOB NOT NULL,
  "SERIALIZED_CONTEXT" CLOB
)
;

-- ----------------------------
-- Table structure for BATCH_STEP_EXECUTION_SEQ
-- ----------------------------
CREATE TABLE "BATCH_STEP_EXECUTION_SEQ" (
  "ID" NUMBER(20) NOT NULL,
  "UNIQUE_KEY" NCHAR(1) NOT NULL
)
;

-- ----------------------------
-- Table structure for DATABASECHANGELOG
-- ----------------------------
CREATE TABLE "DATABASECHANGELOG" (
  "ID" VARCHAR2(255) NOT NULL,
  "AUTHOR" VARCHAR2(255) NOT NULL,
  "FILENAME" VARCHAR2(255) NOT NULL,
  "DATEEXECUTED" DATE NOT NULL,
  "ORDEREXECUTED" NUMBER(11) NOT NULL,
  "EXECTYPE" VARCHAR2(10) NOT NULL,
  "MD5SUM" VARCHAR2(35),
  "DESCRIPTION" VARCHAR2(255),
  "COMMENTS" VARCHAR2(255),
  "TAG" VARCHAR2(255),
  "LIQUIBASE" VARCHAR2(20),
  "CONTEXTS" VARCHAR2(255),
  "LABELS" VARCHAR2(255),
  "DEPLOYMENT_ID" VARCHAR2(10)
)
;

-- ----------------------------
-- Table structure for DATABASECHANGELOGLOCK
-- ----------------------------
CREATE TABLE "DATABASECHANGELOGLOCK" (
  "ID" NUMBER(11) NOT NULL,
  "LOCKED" NUMBER(4) NOT NULL,
  "LOCKGRANTED" DATE,
  "LOCKEDBY" VARCHAR2(255)
)
;

-- ----------------------------
-- Table structure for leaf_alloc
-- ----------------------------
CREATE TABLE "LEAF_ALLOC" (
  "BIZ_TAG" VARCHAR2(128) NOT NULL,
  "MAX_ID" NUMBER(20) NOT NULL,
  "STEP" NUMBER(11) NOT NULL,
  "DESCRIPTION" VARCHAR2(256),
  "UPDATE_TIME" VARCHAR2(64)
)
;

-- ----------------------------
-- Table structure for scheduled_tasks
-- ----------------------------
CREATE TABLE "SCHEDULED_TASKS" (
  "TASK_NAME" VARCHAR2(255) NOT NULL,
  "TASK_INSTANCE" VARCHAR2(255) NOT NULL,
  "TASK_DATA" BLOB,
  "EXECUTION_TIME" DATE NOT NULL,
  "PICKED" NUMBER(4) NOT NULL,
  "PICKED_BY" VARCHAR2(255),
  "LAST_SUCCESS" DATE,
  "LAST_FAILURE" DATE,
  "CONSECUTIVE_FAILURES" NUMBER(11),
  "LAST_HEARTBEAT" DATE,
  "VERSION" NUMBER(20) NOT NULL
)
;

-- ----------------------------
-- Table structure for t_dwd_external_valuation_metric
-- ----------------------------
CREATE TABLE "T_DWD_EXTERNAL_VALUATION_METRIC" (
  "ID" NUMBER(20) NOT NULL,
  "VALUATION_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "SHEET_NAME" VARCHAR2(128),
  "ROW_DATA_NUMBER" NUMBER(11),
  "METRIC_NAME" VARCHAR2(256),
  "METRIC_TYPE" VARCHAR2(64),
  "METRIC_CODE" VARCHAR2(128),
  "METRIC_STANDARD_NAME" VARCHAR2(512),
  "STANDARD_VALUE_TEXT" VARCHAR2(512),
  "STANDARD_VALUE_NUM" NUMBER,
  "STANDARD_VALUE_UNIT" VARCHAR2(64),
  "STANDARD_VALUES_JSON" CLOB,
  "MAPPING_RULE_ID" NUMBER(20),
  "MAPPING_SOURCE_ID" NUMBER(20),
  "MAPPING_STATUS" VARCHAR2(32),
  "MAPPING_REASON" VARCHAR2(512),
  "MAPPING_CONFIDENCE" NUMBER,
  "RAW_VALUES_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_dwd_external_valuation_subject
-- ----------------------------
CREATE TABLE "T_DWD_EXTERNAL_VALUATION_SUBJECT" (
  "ID" NUMBER(20) NOT NULL,
  "VALUATION_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "SHEET_NAME" VARCHAR2(128),
  "ROW_DATA_NUMBER" NUMBER(11),
  "SUBJECT_CODE" VARCHAR2(128),
  "SUBJECT_NAME" VARCHAR2(512),
  "LEVEL_NO" NUMBER(11),
  "PARENT_CODE" VARCHAR2(128),
  "ROOT_CODE" VARCHAR2(128),
  "SEGMENT_COUNT" NUMBER(11),
  "PATH_CODES_JSON" CLOB,
  "IS_LEAF" NUMBER(4),
  "STANDARD_CODE" VARCHAR2(128),
  "STANDARD_NAME" VARCHAR2(512),
  "STANDARD_VALUES_JSON" CLOB,
  "MAPPING_RULE_ID" NUMBER(20),
  "MAPPING_SOURCE_ID" NUMBER(20),
  "MAPPING_STATUS" VARCHAR2(32),
  "MAPPING_REASON" VARCHAR2(512),
  "MAPPING_CONFIDENCE" NUMBER,
  "RAW_VALUES_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_etl_workflow_definition
-- ----------------------------
CREATE TABLE "T_ETL_WORKFLOW_DEFINITION" (
  "WORKFLOW_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_CODE" VARCHAR2(128) NOT NULL,
  "WORKFLOW_NAME" VARCHAR2(256) NOT NULL,
  "WORKFLOW_VERSION_NO" NUMBER(11) NOT NULL,
  "PLATFORM_TYPE" VARCHAR2(64) NOT NULL,
  "DESCRIPTION" CLOB,
  "ENABLED" NUMBER(4) NOT NULL,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_etl_workflow_engine_binding
-- ----------------------------
CREATE TABLE "T_ETL_WORKFLOW_ENGINE_BINDING" (
  "BINDING_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_ID" VARCHAR2(64) NOT NULL,
  "PLATFORM_TYPE" VARCHAR2(64) NOT NULL,
  "EXTERNAL_WORKFLOW_ID" VARCHAR2(256),
  "EXTERNAL_PROJECT_CODE" VARCHAR2(128),
  "EXTERNAL_NAMESPACE" VARCHAR2(128),
  "EXTERNAL_JOB_GROUP" VARCHAR2(128),
  "EXTERNAL_JOB_HANDLER" VARCHAR2(128),
  "CONFIG_JSON" CLOB,
  "ATTRIBUTES_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_etl_workflow_instance
-- ----------------------------
CREATE TABLE "T_ETL_WORKFLOW_INSTANCE" (
  "INSTANCE_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_CODE" VARCHAR2(128) NOT NULL,
  "WORKFLOW_VERSION_NO" NUMBER(11) NOT NULL,
  "PLATFORM_TYPE" VARCHAR2(64) NOT NULL,
  "BUSINESS_KEY" VARCHAR2(256),
  "CURRENT_STAGE_CODE" VARCHAR2(64),
  "EXTERNAL_INSTANCE_ID" VARCHAR2(256),
  "EXTERNAL_WORKFLOW_ID" VARCHAR2(256),
  "STATUS" VARCHAR2(32),
  "RAW_STATUS" VARCHAR2(64),
  "TRIGGER_TIME" DATE,
  "START_TIME" DATE,
  "END_TIME" DATE,
  "MESSAGE" CLOB,
  "CONTEXT_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_etl_workflow_stage
-- ----------------------------
CREATE TABLE "T_ETL_WORKFLOW_STAGE" (
  "STAGE_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_ID" VARCHAR2(64) NOT NULL,
  "STAGE_CODE" VARCHAR2(64) NOT NULL,
  "STAGE_NAME" VARCHAR2(128) NOT NULL,
  "STAGE_ORDER" NUMBER(11) NOT NULL,
  "DESCRIPTION" VARCHAR2(512),
  "RETRYABLE" NUMBER(4) NOT NULL,
  "TIMEOUT_SECONDS" NUMBER(11),
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_etl_workflow_stage_log
-- ----------------------------
CREATE TABLE "T_ETL_WORKFLOW_STAGE_LOG" (
  "LOG_ID" VARCHAR2(64) NOT NULL,
  "INSTANCE_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_ID" VARCHAR2(64) NOT NULL,
  "WORKFLOW_CODE" VARCHAR2(128) NOT NULL,
  "WORKFLOW_VERSION_NO" NUMBER(11) NOT NULL,
  "STAGE_CODE" VARCHAR2(64) NOT NULL,
  "STAGE_NAME" VARCHAR2(128),
  "STAGE_ORDER" NUMBER(11),
  "STATUS" VARCHAR2(32),
  "RAW_STATUS" VARCHAR2(64),
  "MESSAGE" CLOB,
  "START_TIME" DATE,
  "END_TIME" DATE,
  "PAYLOAD_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_file_parse_case
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_CASE" (
  "ID" NUMBER(20) NOT NULL,
  "PROFILE_ID" NUMBER(20) NOT NULL,
  "SAMPLE_FILE_ID" NUMBER(20),
  "SAMPLE_FILE_NAME" VARCHAR2(256),
  "EXPECTED_SHEET_NAME" VARCHAR2(128),
  "EXPECTED_HEADER_ROW" NUMBER(11),
  "EXPECTED_DATA_START_ROW" NUMBER(11),
  "EXPECTED_SUBJECT_COUNT" NUMBER(11),
  "EXPECTED_METRIC_COUNT" NUMBER(11),
  "EXPECTED_OUTPUT_HASH" VARCHAR2(128),
  "STATUS" VARCHAR2(32),
  "CREATER" VARCHAR2(128),
  "CREATE_TIME" DATE,
  "MODIFIER" VARCHAR2(128),
  "MODIFY_TIME" DATE
)
;
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."PROFILE_ID" IS '模板主表ID';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."SAMPLE_FILE_ID" IS '样例文件ID';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."SAMPLE_FILE_NAME" IS '样例文件名';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."EXPECTED_SHEET_NAME" IS '期望sheet名';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."EXPECTED_HEADER_ROW" IS '期望表头行';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."EXPECTED_DATA_START_ROW" IS '期望数据起始行';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."EXPECTED_SUBJECT_COUNT" IS '期望科目数';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."EXPECTED_METRIC_COUNT" IS '期望指标数';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."EXPECTED_OUTPUT_HASH" IS '期望输出哈希';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."STATUS" IS '样例状态';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."CREATER" IS '创建人';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "T_FILE_PARSE_CASE"."MODIFY_TIME" IS '修改时间';
COMMENT ON TABLE "T_FILE_PARSE_CASE" IS '文件解析规则回归样例表';

-- ----------------------------
-- Table structure for t_file_parse_profile
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_PROFILE" (
  "ID" NUMBER(20) NOT NULL,
  "PROFILE_CODE" VARCHAR2(128) NOT NULL,
  "PROFILE_NAME" VARCHAR2(256) NOT NULL,
  "VERSION" VARCHAR2(64) NOT NULL,
  "FILE_SCENE" VARCHAR2(64) NOT NULL,
  "FILE_TYPE_NAME" VARCHAR2(128) NOT NULL,
  "SOURCE_CHANNEL" VARCHAR2(64),
  "STATUS" VARCHAR2(32),
  "PRIORITY" NUMBER(11),
  "MATCH_EXPR" CLOB,
  "HEADER_EXPR" CLOB,
  "ROW_CLASSIFY_EXPR" CLOB,
  "FIELD_MAP_EXPR" CLOB,
  "TRANSFORM_EXPR" CLOB,
  "TRACE_ENABLED" NUMBER(4),
  "TIMEOUT_MS" NUMBER(20),
  "CHECKSUM" VARCHAR2(128),
  "CREATER" VARCHAR2(128),
  "CREATE_TIME" DATE,
  "MODIFIER" VARCHAR2(128),
  "MODIFY_TIME" DATE,
  "PUBLISHED_TIME" DATE,
  "REQUIRED_HEADERS_JSON" CLOB,
  "SUBJECT_CODE_PATTERN" VARCHAR2(256)
)
;
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."PROFILE_CODE" IS '模板编码';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."PROFILE_NAME" IS '模板名称';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."VERSION" IS '版本号';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."FILE_SCENE" IS '文件场景';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."FILE_TYPE_NAME" IS '文件类型名称';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."SOURCE_CHANNEL" IS '来源渠道';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."STATUS" IS '模板状态';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."PRIORITY" IS '优先级';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."MATCH_EXPR" IS '模板匹配表达式';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."HEADER_EXPR" IS '表头识别表达式';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."ROW_CLASSIFY_EXPR" IS '行分类表达式';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."FIELD_MAP_EXPR" IS '字段映射表达式';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."TRANSFORM_EXPR" IS '值转换表达式';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."TRACE_ENABLED" IS '是否开启追踪';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."TIMEOUT_MS" IS '超时时间毫秒数';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."CHECKSUM" IS '校验值';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."CREATER" IS '创建人';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."PUBLISHED_TIME" IS '发布时间';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."REQUIRED_HEADERS_JSON" IS '必选表头字段JSON';
COMMENT ON COLUMN "T_FILE_PARSE_PROFILE"."SUBJECT_CODE_PATTERN" IS '科目代码正则';
COMMENT ON TABLE "T_FILE_PARSE_PROFILE" IS '文件解析模板主表';

-- ----------------------------
-- Table structure for t_file_parse_publish_log
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_PUBLISH_LOG" (
  "ID" NUMBER(20) NOT NULL,
  "PROFILE_ID" NUMBER(20) NOT NULL,
  "VERSION" VARCHAR2(64) NOT NULL,
  "PUBLISH_STATUS" VARCHAR2(32),
  "PUBLISH_TIME" DATE,
  "PUBLISHER" VARCHAR2(128),
  "PUBLISH_COMMENT" VARCHAR2(512),
  "VALIDATION_RESULT_JSON" CLOB,
  "ROLLBACK_FROM_VERSION" VARCHAR2(64)
)
;
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."PROFILE_ID" IS '模板主表ID';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."VERSION" IS '版本号';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."PUBLISH_STATUS" IS '发布状态';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."PUBLISH_TIME" IS '发布时间';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."PUBLISHER" IS '发布人';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."PUBLISH_COMMENT" IS '发布说明';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."VALIDATION_RESULT_JSON" IS '校验结果';
COMMENT ON COLUMN "T_FILE_PARSE_PUBLISH_LOG"."ROLLBACK_FROM_VERSION" IS '回滚来源版本';
COMMENT ON TABLE "T_FILE_PARSE_PUBLISH_LOG" IS '文件解析规则发布日志表';

-- ----------------------------
-- Table structure for t_file_parse_rule
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_RULE" (
  "ID" NUMBER(20) NOT NULL,
  "CREATER" VARCHAR2(128),
  "CREATE_TIME" DATE,
  "MODIFIER" VARCHAR2(128),
  "MODIFY_TIME" DATE,
  "FILE_SCENE" VARCHAR2(64) NOT NULL,
  "FILE_TYPE_NAME" VARCHAR2(128) NOT NULL,
  "REGION_NAME" VARCHAR2(64) NOT NULL,
  "COLUMN_MAP" VARCHAR2(128) NOT NULL,
  "COLUMN_MAP_NAME" VARCHAR2(256) NOT NULL,
  "STATUS" NUMBER(4),
  "MULTI_INDEX" NUMBER(4),
  "REQUIRED" NUMBER(4)
)
;
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."CREATER" IS '创建人';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."FILE_SCENE" IS '文件场景';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."FILE_TYPE_NAME" IS '文件类型名称';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."REGION_NAME" IS '标准区域名称';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."COLUMN_MAP" IS '标准列编码';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."COLUMN_MAP_NAME" IS '标准列名称';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."STATUS" IS '启用状态';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."MULTI_INDEX" IS '是否多实例指标';
COMMENT ON COLUMN "T_FILE_PARSE_RULE"."REQUIRED" IS '是否必需';
COMMENT ON TABLE "T_FILE_PARSE_RULE" IS '文件解析标准规则表';

-- ----------------------------
-- Table structure for t_file_parse_rule_step
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_RULE_STEP" (
  "ID" NUMBER(20) NOT NULL,
  "PROFILE_ID" NUMBER(20) NOT NULL,
  "RULE_TYPE" VARCHAR2(64) NOT NULL,
  "STEP_NAME" VARCHAR2(128) NOT NULL,
  "PRIORITY" NUMBER(11),
  "ENABLED" NUMBER(4),
  "EXPR_TEXT" CLOB,
  "EXPR_LANG" VARCHAR2(32),
  "INPUT_SCHEMA_JSON" CLOB,
  "OUTPUT_SCHEMA_JSON" CLOB,
  "ERROR_POLICY" VARCHAR2(64),
  "TIMEOUT_MS" NUMBER(20),
  "CREATER" VARCHAR2(128),
  "CREATE_TIME" DATE,
  "MODIFIER" VARCHAR2(128),
  "MODIFY_TIME" DATE
)
;
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."PROFILE_ID" IS '模板主表ID';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."RULE_TYPE" IS '规则类型';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."STEP_NAME" IS '步骤名称';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."PRIORITY" IS '优先级';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."ENABLED" IS '是否启用';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."EXPR_TEXT" IS '表达式文本';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."EXPR_LANG" IS '表达式语言';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."INPUT_SCHEMA_JSON" IS '输入结构';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."OUTPUT_SCHEMA_JSON" IS '输出结构';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."ERROR_POLICY" IS '异常策略';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."TIMEOUT_MS" IS '超时时间毫秒数';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."CREATER" IS '创建人';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_STEP"."MODIFY_TIME" IS '修改时间';
COMMENT ON TABLE "T_FILE_PARSE_RULE_STEP" IS '文件解析规则步骤表';

-- ----------------------------
-- Table structure for t_file_parse_rule_trace
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_RULE_TRACE" (
  "ID" NUMBER(20) NOT NULL,
  "TRACE_SCOPE" VARCHAR2(64),
  "TRACE_TYPE" VARCHAR2(64),
  "PROFILE_ID" NUMBER(20),
  "PROFILE_CODE" VARCHAR2(128),
  "VERSION" VARCHAR2(64),
  "FILE_ID" NUMBER(20),
  "TASK_ID" NUMBER(20),
  "STEP_NAME" VARCHAR2(128),
  "EXPRESSION" CLOB,
  "INPUT_JSON" CLOB,
  "OUTPUT_JSON" CLOB,
  "SUCCESS" NUMBER(4),
  "COST_MS" NUMBER(20),
  "ERROR_MESSAGE" CLOB,
  "TRACE_TIME" DATE
)
;
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."TRACE_SCOPE" IS '追踪范围';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."TRACE_TYPE" IS '追踪类型';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."PROFILE_ID" IS '模板主表ID';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."PROFILE_CODE" IS '模板编码';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."VERSION" IS '版本号';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."FILE_ID" IS '文件主键';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."TASK_ID" IS '任务主键';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."STEP_NAME" IS '步骤名称';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."EXPRESSION" IS '表达式文本';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."INPUT_JSON" IS '输入内容';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."OUTPUT_JSON" IS '输出内容';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."SUCCESS" IS '是否成功';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."COST_MS" IS '耗时毫秒';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."ERROR_MESSAGE" IS '错误信息';
COMMENT ON COLUMN "T_FILE_PARSE_RULE_TRACE"."TRACE_TIME" IS '追踪时间';
COMMENT ON TABLE "T_FILE_PARSE_RULE_TRACE" IS '文件解析规则追踪表';

-- ----------------------------
-- Table structure for t_file_parse_source
-- ----------------------------
CREATE TABLE "T_FILE_PARSE_SOURCE" (
  "ID" NUMBER(20) NOT NULL,
  "FILE_TYPE" VARCHAR2(128) NOT NULL,
  "COLUMN_MAP" VARCHAR2(128) NOT NULL,
  "COLUMN_NAME" VARCHAR2(256) NOT NULL,
  "FILE_EXT_INFO" VARCHAR2(512),
  "STATUS" NUMBER(4),
  "CREATER" VARCHAR2(128),
  "CREATE_TIME" DATE,
  "MODIFIER" VARCHAR2(128),
  "MODIFY_TIME" DATE
)
;
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."ID" IS '主键';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."FILE_TYPE" IS '文件类型';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."COLUMN_MAP" IS '标准列编码';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."COLUMN_NAME" IS '来源列名称';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."FILE_EXT_INFO" IS '扩展信息';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."STATUS" IS '启用状态';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."CREATER" IS '创建人';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "T_FILE_PARSE_SOURCE"."MODIFY_TIME" IS '修改时间';
COMMENT ON TABLE "T_FILE_PARSE_SOURCE" IS '文件解析来源映射表';

-- ----------------------------
-- Table structure for t_ods_mapping_hint
-- ----------------------------
CREATE TABLE "T_ODS_MAPPING_HINT" (
  "ID" NUMBER(20) NOT NULL,
  "SOURCE" VARCHAR2(128),
  "NORMALIZED_KEY" VARCHAR2(256),
  "STANDARD_CODE" VARCHAR2(128),
  "STANDARD_NAME" VARCHAR2(512),
  "SUPPORT_COUNT" NUMBER(11),
  "CONFIDENCE" NUMBER
)
;

-- ----------------------------
-- Table structure for t_ods_mapping_sample
-- ----------------------------
CREATE TABLE "T_ODS_MAPPING_SAMPLE" (
  "ID" NUMBER(20) NOT NULL,
  "ORG_NAME" VARCHAR2(256),
  "ORG_ID" VARCHAR2(128),
  "EXTERNAL_CODE" VARCHAR2(500),
  "EXTERNAL_NAME" VARCHAR2(512),
  "STANDARD_CODE" VARCHAR2(128),
  "STANDARD_NAME" VARCHAR2(512),
  "STANDARD_SYSTEM" VARCHAR2(128),
  "SYSTEM_NAME" VARCHAR2(256)
)
;

-- ----------------------------
-- Table structure for t_ods_standard_subject
-- ----------------------------
CREATE TABLE "T_ODS_STANDARD_SUBJECT" (
  "ID" NUMBER(20) NOT NULL,
  "STANDARD_CODE" VARCHAR2(128),
  "STANDARD_NAME" VARCHAR2(512),
  "PARENT_CODE" VARCHAR2(128),
  "PARENT_NAME" VARCHAR2(512),
  "LEVEL" NUMBER(11),
  "ROOT_CODE" VARCHAR2(128),
  "SEGMENT_COUNT" NUMBER(11),
  "PATH_CODES_JSON" CLOB,
  "PATH_NAMES_JSON" CLOB,
  "PATH_TEXT" CLOB,
  "NORMALIZED_NAME" VARCHAR2(512),
  "NORMALIZED_PATH_TEXT" CLOB,
  "PLACEHOLDER" NUMBER(4)
)
;

-- ----------------------------
-- Table structure for t_ods_valuation_filedata
-- ----------------------------
CREATE TABLE "T_ODS_VALUATION_FILEDATA" (
  "ID" NUMBER(20) NOT NULL,
  "TASK_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "ROW_DATA_NUMBER" NUMBER(11) NOT NULL,
  "ROW_DATA_JSON" CLOB NOT NULL
)
;

-- ----------------------------
-- Table structure for t_ods_valuation_sheet_style
-- ----------------------------
CREATE TABLE "T_ODS_VALUATION_SHEET_STYLE" (
  "ID" NUMBER(20) NOT NULL,
  "TASK_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "SHEET_NAME" VARCHAR2(128) NOT NULL,
  "STYLE_SCOPE" VARCHAR2(32) NOT NULL,
  "SHEET_STYLE_JSON" CLOB NOT NULL,
  "PREVIEW_ROW_COUNT" NUMBER(11),
  "CREATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_parse_queue
-- ----------------------------
CREATE TABLE "T_PARSE_QUEUE" (
  "QUEUE_ID" NUMBER(20) NOT NULL,
  "BUSINESS_KEY" VARCHAR2(256) NOT NULL,
  "TRANSFER_ID" NUMBER(20) NOT NULL,
  "ORIGINAL_NAME" VARCHAR2(512),
  "SOURCE_ID" NUMBER(20),
  "SOURCE_TYPE" VARCHAR2(32),
  "SOURCE_CODE" VARCHAR2(128),
  "ROUTE_ID" NUMBER(20),
  "DELIVERY_ID" NUMBER(20),
  "TAG_ID" NUMBER(20),
  "TAG_CODE" VARCHAR2(128),
  "TAG_NAME" VARCHAR2(256),
  "FILE_STATUS" VARCHAR2(32),
  "DELIVERY_STATUS" VARCHAR2(32),
  "PARSE_STATUS" VARCHAR2(32) NOT NULL,
  "TRIGGER_MODE" VARCHAR2(32) NOT NULL,
  "RETRY_COUNT" NUMBER(11) NOT NULL,
  "CLAIMED_BY" VARCHAR2(128),
  "CLAIMED_AT" DATE,
  "PARSED_AT" DATE,
  "LAST_ERROR_MESSAGE" CLOB,
  "OBJECT_SNAPSHOT_JSON" CLOB,
  "DELIVERY_SNAPSHOT_JSON" CLOB,
  "PARSE_REQUEST_JSON" CLOB,
  "PARSE_RESULT_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_stg_external_valuation
-- ----------------------------
CREATE TABLE "T_STG_EXTERNAL_VALUATION" (
  "ID" NUMBER(20) NOT NULL,
  "TASK_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "WORKBOOK_PATH" VARCHAR2(512),
  "SHEET_NAME" VARCHAR2(128),
  "HEADER_ROW_NUMBER" NUMBER(11),
  "DATA_START_ROW_NUMBER" NUMBER(11),
  "TITLE" VARCHAR2(512)
)
;

-- ----------------------------
-- Table structure for t_stg_external_valuation_basic_info
-- ----------------------------
CREATE TABLE "T_STG_EXTERNAL_VALUATION_BASIC_INFO" (
  "ID" NUMBER(20) NOT NULL,
  "VALUATION_ID" NUMBER(20) NOT NULL,
  "SORT_ORDER" NUMBER(11) NOT NULL,
  "INFO_KEY" VARCHAR2(128),
  "INFO_VALUE" VARCHAR2(512)
)
;

-- ----------------------------
-- Table structure for t_stg_external_valuation_header
-- ----------------------------
CREATE TABLE "T_STG_EXTERNAL_VALUATION_HEADER" (
  "ID" NUMBER(20) NOT NULL,
  "VALUATION_ID" NUMBER(20) NOT NULL,
  "COLUMN_INDEX" NUMBER(11) NOT NULL,
  "HEADER_NAME" VARCHAR2(256),
  "HEADER_DETAIL_JSON" CLOB,
  "HEADER_COLUMN_META_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_stg_external_valuation_metric
-- ----------------------------
CREATE TABLE "T_STG_EXTERNAL_VALUATION_METRIC" (
  "ID" NUMBER(20) NOT NULL,
  "VALUATION_ID" NUMBER(20) NOT NULL,
  "SHEET_NAME" VARCHAR2(128),
  "ROW_DATA_NUMBER" NUMBER(11),
  "METRIC_NAME" VARCHAR2(256),
  "METRIC_TYPE" VARCHAR2(64),
  "METRIC_VALUE" VARCHAR2(512),
  "RAW_VALUES_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_stg_external_valuation_subject
-- ----------------------------
CREATE TABLE "T_STG_EXTERNAL_VALUATION_SUBJECT" (
  "ID" NUMBER(20) NOT NULL,
  "VALUATION_ID" NUMBER(20) NOT NULL,
  "SHEET_NAME" VARCHAR2(128),
  "ROW_DATA_NUMBER" NUMBER(11),
  "SUBJECT_CODE" VARCHAR2(128),
  "SUBJECT_NAME" VARCHAR2(512),
  "LEVEL_NO" NUMBER(11),
  "PARENT_CODE" VARCHAR2(128),
  "ROOT_CODE" VARCHAR2(128),
  "SEGMENT_COUNT" NUMBER(11),
  "PATH_CODES_JSON" CLOB,
  "IS_LEAF" NUMBER(4),
  "RAW_VALUES_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_subject_match_result
-- ----------------------------
CREATE TABLE "T_SUBJECT_MATCH_RESULT" (
  "ID" NUMBER(20) NOT NULL,
  "TASK_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "EXTERNAL_SUBJECT_CODE" VARCHAR2(128),
  "EXTERNAL_SUBJECT_NAME" VARCHAR2(512),
  "EXTERNAL_LEVEL" NUMBER(11),
  "EXTERNAL_IS_LEAF" NUMBER(4),
  "ANCHOR_SUBJECT_CODE" VARCHAR2(128),
  "ANCHOR_SUBJECT_NAME" VARCHAR2(512),
  "ANCHOR_LEVEL" NUMBER(11),
  "ANCHOR_PATH_TEXT" CLOB,
  "ANCHOR_REASON" CLOB,
  "MATCHED_STANDARD_CODE" VARCHAR2(128),
  "MATCHED_STANDARD_NAME" VARCHAR2(512),
  "SCORE" NUMBER,
  "SCORE_NAME" NUMBER,
  "SCORE_PATH" NUMBER,
  "SCORE_KEYWORD" NUMBER,
  "SCORE_CODE" NUMBER,
  "SCORE_HISTORY" NUMBER,
  "SCORE_EMBEDDING" NUMBER,
  "CONFIDENCE_LEVEL" VARCHAR2(32),
  "NEEDS_REVIEW" NUMBER(4),
  "MATCH_REASON" CLOB,
  "CANDIDATE_COUNT" NUMBER(11),
  "TOP_CANDIDATES_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_tr_index
-- ----------------------------
CREATE TABLE "T_TR_INDEX" (
  "ID" NUMBER(20) NOT NULL,
  "ORG_CD" VARCHAR2(30),
  "PD_CD" VARCHAR2(60),
  "BIZ_DATE" VARCHAR2(8),
  "INDX_NM" VARCHAR2(300),
  "INDX_VALU" VARCHAR2(300),
  "SOURCE_TP" VARCHAR2(30),
  "SOURCE_SIGN" VARCHAR2(300),
  "TIME_STAMP" DATE
)
;
COMMENT ON COLUMN "T_TR_INDEX"."ID" IS '主键';
COMMENT ON COLUMN "T_TR_INDEX"."ORG_CD" IS '机构代码';
COMMENT ON COLUMN "T_TR_INDEX"."PD_CD" IS '产品代码';
COMMENT ON COLUMN "T_TR_INDEX"."BIZ_DATE" IS '业务日期';
COMMENT ON COLUMN "T_TR_INDEX"."INDX_NM" IS '指标名称';
COMMENT ON COLUMN "T_TR_INDEX"."INDX_VALU" IS '指标值';
COMMENT ON COLUMN "T_TR_INDEX"."SOURCE_TP" IS '来源类型';
COMMENT ON COLUMN "T_TR_INDEX"."SOURCE_SIGN" IS '来源标记';
COMMENT ON COLUMN "T_TR_INDEX"."TIME_STAMP" IS '时间戳';
COMMENT ON TABLE "T_TR_INDEX" IS '资产估值指标信息（原始数据）';

-- ----------------------------
-- Table structure for t_tr_jjhzgzb
-- ----------------------------
CREATE TABLE "T_TR_JJHZGZB" (
  "ID" NUMBER(20) NOT NULL,
  "ORG_CD" VARCHAR2(30),
  "PD_CD" VARCHAR2(30),
  "BIZ_DATE" VARCHAR2(8),
  "SUBJECT_CD" VARCHAR2(200),
  "SUBJECT_NM" VARCHAR2(300),
  "PA_SUBJECT_CD" VARCHAR2(100),
  "PA_SUBJECT_NM" VARCHAR2(300),
  "N_HLDAMT" NUMBER,
  "N_HLDCST" NUMBER,
  "N_HLDCST_LOCL" NUMBER,
  "N_HLDMKV" NUMBER,
  "N_HLDMKV_LOCL" NUMBER,
  "N_HLDVVA" NUMBER,
  "N_HLDVVA_L" NUMBER,
  "CCY_CD" VARCHAR2(3),
  "N_VALRATE" NUMBER,
  "N_PRICE_COST" NUMBER,
  "N_VALPRICE" NUMBER,
  "N_CB_JZ_BL" NUMBER,
  "N_SZ_JZ_BL" NUMBER,
  "N_ZC_BL" NUMBER,
  "SUSP_INFO" VARCHAR2(300),
  "VALUAT_EQUITY" VARCHAR2(30),
  "FIN_ATTR_ID_D" VARCHAR2(30),
  "FIN_MKT_CD" VARCHAR2(30),
  "TIME_STAMP" DATE,
  "CONS_FLOAT_TP_CD" VARCHAR2(30),
  "SOURCE_TP" VARCHAR2(30),
  "SOURCE_SIGN" VARCHAR2(300),
  "SN" NUMBER(6),
  "DATA_DT" VARCHAR2(8),
  "ISIN_CD" VARCHAR2(30)
)
;
COMMENT ON COLUMN "T_TR_JJHZGZB"."ID" IS '主键';
COMMENT ON COLUMN "T_TR_JJHZGZB"."ORG_CD" IS '机构代码';
COMMENT ON COLUMN "T_TR_JJHZGZB"."PD_CD" IS '产品代码';
COMMENT ON COLUMN "T_TR_JJHZGZB"."BIZ_DATE" IS '业务日期';
COMMENT ON COLUMN "T_TR_JJHZGZB"."SUBJECT_CD" IS '科目代码';
COMMENT ON COLUMN "T_TR_JJHZGZB"."SUBJECT_NM" IS '科目名称';
COMMENT ON COLUMN "T_TR_JJHZGZB"."PA_SUBJECT_CD" IS '父级科目代码';
COMMENT ON COLUMN "T_TR_JJHZGZB"."PA_SUBJECT_NM" IS '父级科目名称';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDAMT" IS '持仓数量';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDCST" IS '原币持仓成本';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDCST_LOCL" IS '本币持仓成本';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDMKV" IS '原币持仓市值';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDMKV_LOCL" IS '本币持仓市值';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDVVA" IS '原币证券估增';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_HLDVVA_L" IS '本币证券估增';
COMMENT ON COLUMN "T_TR_JJHZGZB"."CCY_CD" IS '币种';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_VALRATE" IS '汇率';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_PRICE_COST" IS '单位成本';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_VALPRICE" IS '估值价格';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_CB_JZ_BL" IS '成本占比';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_SZ_JZ_BL" IS '市值占比';
COMMENT ON COLUMN "T_TR_JJHZGZB"."N_ZC_BL" IS '资产占比';
COMMENT ON COLUMN "T_TR_JJHZGZB"."SUSP_INFO" IS '停牌信息';
COMMENT ON COLUMN "T_TR_JJHZGZB"."VALUAT_EQUITY" IS '权益信息';
COMMENT ON COLUMN "T_TR_JJHZGZB"."FIN_ATTR_ID_D" IS '金融属性';
COMMENT ON COLUMN "T_TR_JJHZGZB"."FIN_MKT_CD" IS '交易市场';
COMMENT ON COLUMN "T_TR_JJHZGZB"."TIME_STAMP" IS '时间戳';
COMMENT ON COLUMN "T_TR_JJHZGZB"."CONS_FLOAT_TP_CD" IS '浮动类型';
COMMENT ON COLUMN "T_TR_JJHZGZB"."SOURCE_TP" IS '来源类型';
COMMENT ON COLUMN "T_TR_JJHZGZB"."SOURCE_SIGN" IS '来源标记';
COMMENT ON COLUMN "T_TR_JJHZGZB"."SN" IS '序号';
COMMENT ON COLUMN "T_TR_JJHZGZB"."DATA_DT" IS '数据日期';
COMMENT ON COLUMN "T_TR_JJHZGZB"."ISIN_CD" IS 'ISIN代码';
COMMENT ON TABLE "T_TR_JJHZGZB" IS '基金持仓估值表';

-- ----------------------------
-- Table structure for t_transfer_delivery_record
-- ----------------------------
CREATE TABLE "T_TRANSFER_DELIVERY_RECORD" (
  "DELIVERY_ID" NUMBER(20) NOT NULL,
  "ROUTE_ID" NUMBER(20) NOT NULL,
  "TRANSFER_ID" NUMBER(20),
  "TARGET_TYPE" VARCHAR2(32) NOT NULL,
  "TARGET_CODE" VARCHAR2(128) NOT NULL,
  "EXECUTE_STATUS" VARCHAR2(32) NOT NULL,
  "RETRY_COUNT" NUMBER(11) NOT NULL,
  "REQUEST_SNAPSHOT_JSON" CLOB,
  "RESPONSE_SNAPSHOT_JSON" CLOB,
  "ERROR_MESSAGE" CLOB,
  "DELIVERED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_mail_info
-- ----------------------------
CREATE TABLE "T_TRANSFER_MAIL_INFO" (
  "TRANSFER_ID" NUMBER(20) NOT NULL,
  "MAIL_ID" VARCHAR2(128),
  "MAIL_FROM" VARCHAR2(512),
  "MAIL_TO" CLOB,
  "MAIL_CC" CLOB,
  "MAIL_BCC" CLOB,
  "MAIL_SUBJECT" CLOB,
  "MAIL_BODY" CLOB,
  "MAIL_PROTOCOL" VARCHAR2(32),
  "MAIL_FOLDER" VARCHAR2(256)
)
;

-- ----------------------------
-- Table structure for t_transfer_object
-- ----------------------------
CREATE TABLE "T_TRANSFER_OBJECT" (
  "TRANSFER_ID" NUMBER(20) NOT NULL,
  "SOURCE_ID" NUMBER(20),
  "SOURCE_TYPE" VARCHAR2(32),
  "SOURCE_CODE" VARCHAR2(128),
  "ORIGINAL_NAME" VARCHAR2(512) NOT NULL,
  "EXTENSION" VARCHAR2(32),
  "MIME_TYPE" VARCHAR2(512),
  "SIZE_BYTES" NUMBER(20),
  "FINGERPRINT" VARCHAR2(128) NOT NULL,
  "SOURCE_REF" CLOB,
  "LOCAL_TEMP_PATH" CLOB,
  "STATUS" VARCHAR2(32) NOT NULL,
  "RECEIVED_AT" DATE,
  "STORED_AT" DATE,
  "ROUTE_ID" NUMBER(20),
  "ERROR_MESSAGE" CLOB,
  "PROBE_RESULT_JSON" CLOB,
  "FILE_META_JSON" CLOB,
  "REAL_STORAGE_PATH" CLOB,
  "BUSINESS_DATE" DATE,
  "BUSINESS_ID" VARCHAR2(128),
  "RECEIVE_DATE" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_object_tag
-- ----------------------------
CREATE TABLE "T_TRANSFER_OBJECT_TAG" (
  "ID" NUMBER(20) NOT NULL,
  "TRANSFER_ID" NUMBER(20) NOT NULL,
  "TAG_ID" NUMBER(20) NOT NULL,
  "TAG_CODE" VARCHAR2(128) NOT NULL,
  "TAG_NAME" VARCHAR2(256) NOT NULL,
  "TAG_VALUE" VARCHAR2(256) NOT NULL,
  "MATCH_STRATEGY" VARCHAR2(64),
  "MATCH_REASON" CLOB,
  "MATCHED_FIELD" VARCHAR2(128),
  "MATCHED_VALUE" VARCHAR2(512),
  "MATCH_SNAPSHOT_JSON" CLOB,
  "CREATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_route
-- ----------------------------
CREATE TABLE "T_TRANSFER_ROUTE" (
  "ROUTE_ID" NUMBER(20) NOT NULL,
  "RULE_ID" NUMBER(20) NOT NULL,
  "TARGET_TYPE" VARCHAR2(32) NOT NULL,
  "TARGET_CODE" VARCHAR2(128) NOT NULL,
  "ENABLED" NUMBER(4) NOT NULL,
  "TARGET_PATH" CLOB,
  "RENAME_PATTERN" VARCHAR2(512),
  "ROUTE_STATUS" VARCHAR2(32) NOT NULL,
  "ROUTE_META_JSON" CLOB,
  "SOURCE_ID" NUMBER(20),
  "SOURCE_TYPE" VARCHAR2(32),
  "SOURCE_CODE" VARCHAR2(128),
  "POLL_CRON" VARCHAR2(128)
)
;

-- ----------------------------
-- Table structure for t_transfer_rule
-- ----------------------------
CREATE TABLE "T_TRANSFER_RULE" (
  "RULE_ID" NUMBER(20) NOT NULL,
  "RULE_CODE" VARCHAR2(128) NOT NULL,
  "RULE_NAME" VARCHAR2(256) NOT NULL,
  "RULE_VERSION" VARCHAR2(64),
  "ENABLED" NUMBER(4) NOT NULL,
  "PRIORITY" NUMBER(11) NOT NULL,
  "MATCH_STRATEGY" VARCHAR2(64),
  "SCRIPT_LANGUAGE" VARCHAR2(64),
  "SCRIPT_BODY" CLOB,
  "EFFECTIVE_FROM" DATE,
  "EFFECTIVE_TO" DATE,
  "RULE_META_JSON" CLOB
)
;

-- ----------------------------
-- Table structure for t_transfer_run_log
-- ----------------------------
CREATE TABLE "T_TRANSFER_RUN_LOG" (
  "RUN_LOG_ID" NUMBER(20) NOT NULL,
  "SOURCE_ID" NUMBER(20),
  "SOURCE_TYPE" VARCHAR2(32),
  "SOURCE_CODE" VARCHAR2(128),
  "SOURCE_NAME" VARCHAR2(256),
  "TRANSFER_ID" NUMBER(20),
  "ROUTE_ID" NUMBER(20),
  "TRIGGER_TYPE" VARCHAR2(32),
  "RUN_STAGE" VARCHAR2(32) NOT NULL,
  "RUN_STATUS" VARCHAR2(32) NOT NULL,
  "LOG_MESSAGE" CLOB,
  "ERROR_MESSAGE" CLOB,
  "CREATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_source
-- ----------------------------
CREATE TABLE "T_TRANSFER_SOURCE" (
  "SOURCE_ID" NUMBER(20) NOT NULL,
  "SOURCE_CODE" VARCHAR2(128) NOT NULL,
  "SOURCE_NAME" VARCHAR2(256) NOT NULL,
  "SOURCE_TYPE" VARCHAR2(32) NOT NULL,
  "ENABLED" NUMBER(4) NOT NULL,
  "POLL_CRON" VARCHAR2(128),
  "CONNECTION_CONFIG_JSON" CLOB,
  "SOURCE_META_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE,
  "INGEST_STATUS" VARCHAR2(32) NOT NULL,
  "INGEST_STARTED_AT" DATE,
  "INGEST_FINISHED_AT" DATE,
  "INGEST_TRIGGER_TYPE" VARCHAR2(32)
)
;

-- ----------------------------
-- Table structure for t_transfer_source_checkpoint
-- ----------------------------
CREATE TABLE "T_TRANSFER_SOURCE_CHECKPOINT" (
  "CHECKPOINT_ID" NUMBER(20) NOT NULL,
  "SOURCE_ID" NUMBER(20) NOT NULL,
  "SOURCE_TYPE" VARCHAR2(32) NOT NULL,
  "CHECKPOINT_KEY" VARCHAR2(128) NOT NULL,
  "CHECKPOINT_VALUE" CLOB,
  "CHECKPOINT_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_source_checkpoint_item
-- ----------------------------
CREATE TABLE "T_TRANSFER_SOURCE_CHECKPOINT_ITEM" (
  "CHECKPOINT_ITEM_ID" NUMBER(20) NOT NULL,
  "SOURCE_ID" NUMBER(20) NOT NULL,
  "SOURCE_TYPE" VARCHAR2(32) NOT NULL,
  "ITEM_KEY" VARCHAR2(512) NOT NULL,
  "ITEM_REF" CLOB,
  "ITEM_NAME" VARCHAR2(512),
  "ITEM_SIZE" NUMBER(20),
  "ITEM_MIME_TYPE" VARCHAR2(512),
  "ITEM_FINGERPRINT" VARCHAR2(128),
  "ITEM_META_JSON" CLOB,
  "TRIGGER_TYPE" VARCHAR2(32),
  "PROCESSED_AT" DATE NOT NULL,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_tag
-- ----------------------------
CREATE TABLE "T_TRANSFER_TAG" (
  "TAG_ID" NUMBER(20) NOT NULL,
  "TAG_CODE" VARCHAR2(128) NOT NULL,
  "TAG_NAME" VARCHAR2(256) NOT NULL,
  "TAG_VALUE" VARCHAR2(256) NOT NULL,
  "ENABLED" NUMBER(4) NOT NULL,
  "PRIORITY" NUMBER(11) NOT NULL,
  "MATCH_STRATEGY" VARCHAR2(64),
  "SCRIPT_LANGUAGE" VARCHAR2(64),
  "SCRIPT_BODY" CLOB,
  "REGEX_TARGET_FIELD" VARCHAR2(128),
  "REGEX_PATTERN" CLOB,
  "SCOPE_TYPE" VARCHAR2(64),
  "SCOPE_CONFIG_JSON" CLOB,
  "EFFECTIVE_FROM" DATE,
  "EFFECTIVE_TO" DATE,
  "TAG_META_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_transfer_target
-- ----------------------------
CREATE TABLE "T_TRANSFER_TARGET" (
  "TARGET_ID" NUMBER(20) NOT NULL,
  "TARGET_CODE" VARCHAR2(128) NOT NULL,
  "TARGET_NAME" VARCHAR2(256) NOT NULL,
  "TARGET_TYPE" VARCHAR2(32) NOT NULL,
  "ENABLED" NUMBER(4) NOT NULL,
  "TARGET_PATH_TEMPLATE" CLOB,
  "CONNECTION_CONFIG_JSON" CLOB,
  "TARGET_META_JSON" CLOB,
  "CREATED_AT" DATE,
  "UPDATED_AT" DATE
)
;

-- ----------------------------
-- Table structure for t_valset_file_ingest_log
-- ----------------------------
CREATE TABLE "T_VALSET_FILE_INGEST_LOG" (
  "INGEST_ID" NUMBER(20) NOT NULL,
  "FILE_ID" NUMBER(20) NOT NULL,
  "SOURCE_CHANNEL" VARCHAR2(64) NOT NULL,
  "SOURCE_URI" CLOB,
  "CHANNEL_MESSAGE_ID" VARCHAR2(256),
  "INGEST_STATUS" VARCHAR2(32) NOT NULL,
  "INGEST_TIME" DATE NOT NULL,
  "INGEST_META_JSON" CLOB,
  "CREATED_BY" VARCHAR2(128),
  "ERROR_MESSAGE" CLOB
)
;

-- ----------------------------
-- Primary Key structure for table BATCH_JOB_EXECUTION
-- ----------------------------
ALTER TABLE "BATCH_JOB_EXECUTION" ADD PRIMARY KEY ("JOB_EXECUTION_ID");

-- ----------------------------
-- Indexes structure for table BATCH_JOB_EXECUTION
-- ----------------------------
CREATE INDEX "JOB_INST_EXEC_FK"
  ON "BATCH_JOB_EXECUTION" ("JOB_INSTANCE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table BATCH_JOB_EXECUTION_CONTEXT
-- ----------------------------
ALTER TABLE "BATCH_JOB_EXECUTION_CONTEXT" ADD PRIMARY KEY ("JOB_EXECUTION_ID");

-- ----------------------------
-- Indexes structure for table BATCH_JOB_EXECUTION_PARAMS
-- ----------------------------
CREATE INDEX "JOB_EXEC_PARAMS_FK"
  ON "BATCH_JOB_EXECUTION_PARAMS" ("JOB_EXECUTION_ID" ASC);

-- ----------------------------
-- Indexes structure for table BATCH_JOB_EXECUTION_SEQ
-- ----------------------------
CREATE UNIQUE INDEX "UNIQUE_KEY_UN"
  ON "BATCH_JOB_EXECUTION_SEQ" ("UNIQUE_KEY" ASC);

-- ----------------------------
-- Primary Key structure for table BATCH_JOB_INSTANCE
-- ----------------------------
ALTER TABLE "BATCH_JOB_INSTANCE" ADD PRIMARY KEY ("JOB_INSTANCE_ID");

-- ----------------------------
-- Indexes structure for table BATCH_JOB_INSTANCE
-- ----------------------------
CREATE UNIQUE INDEX "JOB_INST_UN"
  ON "BATCH_JOB_INSTANCE" ("JOB_NAME" ASC, "JOB_KEY" ASC);

-- ----------------------------
-- Indexes structure for table BATCH_JOB_SEQ
-- ----------------------------
CREATE UNIQUE INDEX "UNIQUE_KEY_UN"
  ON "BATCH_JOB_SEQ" ("UNIQUE_KEY" ASC);

-- ----------------------------
-- Primary Key structure for table BATCH_STEP_EXECUTION
-- ----------------------------
ALTER TABLE "BATCH_STEP_EXECUTION" ADD PRIMARY KEY ("STEP_EXECUTION_ID");

-- ----------------------------
-- Indexes structure for table BATCH_STEP_EXECUTION
-- ----------------------------
CREATE INDEX "JOB_EXEC_STEP_FK"
  ON "BATCH_STEP_EXECUTION" ("JOB_EXECUTION_ID" ASC);

-- ----------------------------
-- Primary Key structure for table BATCH_STEP_EXECUTION_CONTEXT
-- ----------------------------
ALTER TABLE "BATCH_STEP_EXECUTION_CONTEXT" ADD PRIMARY KEY ("STEP_EXECUTION_ID");

-- ----------------------------
-- Indexes structure for table BATCH_STEP_EXECUTION_SEQ
-- ----------------------------
CREATE UNIQUE INDEX "UNIQUE_KEY_UN"
  ON "BATCH_STEP_EXECUTION_SEQ" ("UNIQUE_KEY" ASC);

-- ----------------------------
-- Primary Key structure for table DATABASECHANGELOGLOCK
-- ----------------------------
ALTER TABLE "DATABASECHANGELOGLOCK" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table leaf_alloc
-- ----------------------------
ALTER TABLE "LEAF_ALLOC" ADD PRIMARY KEY ("BIZ_TAG");

-- ----------------------------
-- Primary Key structure for table scheduled_tasks
-- ----------------------------
ALTER TABLE "SCHEDULED_TASKS" ADD PRIMARY KEY ("TASK_NAME", "TASK_INSTANCE");

-- ----------------------------
-- Indexes structure for table scheduled_tasks
-- ----------------------------
CREATE INDEX "EXECUTION_TIME_IDX"
  ON "SCHEDULED_TASKS" ("EXECUTION_TIME" ASC);
CREATE INDEX "LAST_HEARTBEAT_IDX"
  ON "SCHEDULED_TASKS" ("LAST_HEARTBEAT" ASC);

-- ----------------------------
-- Primary Key structure for table t_dwd_external_valuation_metric
-- ----------------------------
ALTER TABLE "T_DWD_EXTERNAL_VALUATION_METRIC" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table t_dwd_external_valuation_subject
-- ----------------------------
ALTER TABLE "T_DWD_EXTERNAL_VALUATION_SUBJECT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table t_etl_workflow_definition
-- ----------------------------
ALTER TABLE "T_ETL_WORKFLOW_DEFINITION" ADD PRIMARY KEY ("WORKFLOW_ID");

-- ----------------------------
-- Indexes structure for table t_etl_workflow_definition
-- ----------------------------
CREATE UNIQUE INDEX "UK_ETL_WORKFLOW_DEFINITION_CODE_VERSION"
  ON "T_ETL_WORKFLOW_DEFINITION" ("WORKFLOW_CODE" ASC, "WORKFLOW_VERSION_NO" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_DEFINITION_CODE"
  ON "T_ETL_WORKFLOW_DEFINITION" ("WORKFLOW_CODE" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_DEFINITION_PLATFORM"
  ON "T_ETL_WORKFLOW_DEFINITION" ("PLATFORM_TYPE" ASC);

-- ----------------------------
-- Primary Key structure for table t_etl_workflow_engine_binding
-- ----------------------------
ALTER TABLE "T_ETL_WORKFLOW_ENGINE_BINDING" ADD PRIMARY KEY ("BINDING_ID");

-- ----------------------------
-- Indexes structure for table t_etl_workflow_engine_binding
-- ----------------------------
CREATE UNIQUE INDEX "UK_ETL_WORKFLOW_BINDING_WORKFLOW"
  ON "T_ETL_WORKFLOW_ENGINE_BINDING" ("WORKFLOW_ID" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_BINDING_PLATFORM"
  ON "T_ETL_WORKFLOW_ENGINE_BINDING" ("PLATFORM_TYPE" ASC);

-- ----------------------------
-- Primary Key structure for table t_etl_workflow_instance
-- ----------------------------
ALTER TABLE "T_ETL_WORKFLOW_INSTANCE" ADD PRIMARY KEY ("INSTANCE_ID");

-- ----------------------------
-- Indexes structure for table t_etl_workflow_instance
-- ----------------------------
CREATE INDEX "IDX_ETL_WORKFLOW_INSTANCE_CODE_VERSION"
  ON "T_ETL_WORKFLOW_INSTANCE" ("WORKFLOW_CODE" ASC, "WORKFLOW_VERSION_NO" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_INSTANCE_STATUS"
  ON "T_ETL_WORKFLOW_INSTANCE" ("STATUS" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_INSTANCE_EXTERNAL"
  ON "T_ETL_WORKFLOW_INSTANCE" ("EXTERNAL_INSTANCE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_etl_workflow_stage
-- ----------------------------
ALTER TABLE "T_ETL_WORKFLOW_STAGE" ADD PRIMARY KEY ("STAGE_ID");

-- ----------------------------
-- Indexes structure for table t_etl_workflow_stage
-- ----------------------------
CREATE UNIQUE INDEX "UK_ETL_WORKFLOW_STAGE_CODE"
  ON "T_ETL_WORKFLOW_STAGE" ("WORKFLOW_ID" ASC, "STAGE_CODE" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_STAGE_WORKFLOW_ORDER"
  ON "T_ETL_WORKFLOW_STAGE" ("WORKFLOW_ID" ASC, "STAGE_ORDER" ASC);

-- ----------------------------
-- Primary Key structure for table t_etl_workflow_stage_log
-- ----------------------------
ALTER TABLE "T_ETL_WORKFLOW_STAGE_LOG" ADD PRIMARY KEY ("LOG_ID");

-- ----------------------------
-- Indexes structure for table t_etl_workflow_stage_log
-- ----------------------------
CREATE INDEX "IDX_ETL_WORKFLOW_STAGE_LOG_INSTANCE"
  ON "T_ETL_WORKFLOW_STAGE_LOG" ("INSTANCE_ID" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_STAGE_LOG_STAGE"
  ON "T_ETL_WORKFLOW_STAGE_LOG" ("STAGE_CODE" ASC);
CREATE INDEX "IDX_ETL_WORKFLOW_STAGE_LOG_STATUS"
  ON "T_ETL_WORKFLOW_STAGE_LOG" ("STATUS" ASC);

-- ----------------------------
-- Primary Key structure for table t_file_parse_case
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_CASE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_file_parse_case
-- ----------------------------
CREATE INDEX "IDX_FILE_PARSE_CASE_PROFILE_SAMPLE"
  ON "T_FILE_PARSE_CASE" ("PROFILE_ID" ASC, "SAMPLE_FILE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_file_parse_profile
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_PROFILE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_file_parse_profile
-- ----------------------------
CREATE UNIQUE INDEX "UK_FILE_PARSE_PROFILE_CODE_VERSION"
  ON "T_FILE_PARSE_PROFILE" ("PROFILE_CODE" ASC, "VERSION" ASC);
CREATE INDEX "IDX_FILE_PARSE_PROFILE_STATUS_MODIFY"
  ON "T_FILE_PARSE_PROFILE" ("STATUS" ASC, "MODIFY_TIME" ASC);

-- ----------------------------
-- Primary Key structure for table t_file_parse_publish_log
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_PUBLISH_LOG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_file_parse_publish_log
-- ----------------------------
CREATE INDEX "IDX_FILE_PARSE_PUBLISH_LOG_PROFILE_TIME"
  ON "T_FILE_PARSE_PUBLISH_LOG" ("PROFILE_ID" ASC, "PUBLISH_TIME" ASC, "ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_file_parse_rule
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_RULE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table t_file_parse_rule_step
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_RULE_STEP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_file_parse_rule_step
-- ----------------------------
CREATE UNIQUE INDEX "UK_FILE_PARSE_RULE_STEP_PROFILE_NAME"
  ON "T_FILE_PARSE_RULE_STEP" ("PROFILE_ID" ASC, "STEP_NAME" ASC);
CREATE INDEX "IDX_FILE_PARSE_RULE_STEP_PROFILE_PRIORITY"
  ON "T_FILE_PARSE_RULE_STEP" ("PROFILE_ID" ASC, "PRIORITY" ASC, "ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_file_parse_rule_trace
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_RULE_TRACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_file_parse_rule_trace
-- ----------------------------
CREATE INDEX "IDX_FILE_PARSE_RULE_TRACE_PROFILE_TIME"
  ON "T_FILE_PARSE_RULE_TRACE" ("PROFILE_ID" ASC, "TRACE_TIME" ASC, "ID" ASC);
CREATE INDEX "IDX_FILE_PARSE_RULE_TRACE_FILE_TASK_TYPE"
  ON "T_FILE_PARSE_RULE_TRACE" ("FILE_ID" ASC, "TASK_ID" ASC, "TRACE_TYPE" ASC, "TRACE_TIME" ASC);

-- ----------------------------
-- Primary Key structure for table t_file_parse_source
-- ----------------------------
ALTER TABLE "T_FILE_PARSE_SOURCE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_file_parse_source
-- ----------------------------
CREATE INDEX "IDX_FILE_PARSE_SOURCE_COLUMN_MAP"
  ON "T_FILE_PARSE_SOURCE" ("COLUMN_MAP" ASC);
CREATE INDEX "IDX_FILE_PARSE_SOURCE_COLUMN_NAME"
  ON "T_FILE_PARSE_SOURCE" ("COLUMN_NAME" ASC);

-- ----------------------------
-- Primary Key structure for table t_ods_mapping_hint
-- ----------------------------
ALTER TABLE "T_ODS_MAPPING_HINT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_ods_mapping_hint
-- ----------------------------
CREATE INDEX "IDX_ODS_MAPPING_HINT_KEY_CODE"
  ON "T_ODS_MAPPING_HINT" ("NORMALIZED_KEY" ASC, "STANDARD_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_ods_mapping_sample
-- ----------------------------
ALTER TABLE "T_ODS_MAPPING_SAMPLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_ods_mapping_sample
-- ----------------------------
CREATE INDEX "IDX_ODS_MAPPING_SAMPLE_ORG"
  ON "T_ODS_MAPPING_SAMPLE" ("ORG_NAME" ASC);
CREATE INDEX "IDX_ODS_MAPPING_SAMPLE_EXT_CODE"
  ON "T_ODS_MAPPING_SAMPLE" ("EXTERNAL_CODE" ASC);
CREATE INDEX "IDX_ODS_MAPPING_SAMPLE_STD_CODE"
  ON "T_ODS_MAPPING_SAMPLE" ("STANDARD_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_ods_standard_subject
-- ----------------------------
ALTER TABLE "T_ODS_STANDARD_SUBJECT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_ods_standard_subject
-- ----------------------------
CREATE INDEX "IDX_ODS_STANDARD_SUBJECT_CODE"
  ON "T_ODS_STANDARD_SUBJECT" ("STANDARD_CODE" ASC);
CREATE INDEX "IDX_ODS_STANDARD_SUBJECT_ROOT_LEVEL"
  ON "T_ODS_STANDARD_SUBJECT" ("ROOT_CODE" ASC, "LEVEL" ASC);

-- ----------------------------
-- Primary Key structure for table t_ods_valuation_filedata
-- ----------------------------
ALTER TABLE "T_ODS_VALUATION_FILEDATA" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_ods_valuation_filedata
-- ----------------------------
CREATE INDEX "IDX_ODS_FILEDATA_TASK_ID"
  ON "T_ODS_VALUATION_FILEDATA" ("TASK_ID" ASC);
CREATE INDEX "IDX_ODS_FILEDATA_FILE_ID"
  ON "T_ODS_VALUATION_FILEDATA" ("FILE_ID" ASC);
CREATE INDEX "IDX_ODS_FILEDATA_TASK_ROW"
  ON "T_ODS_VALUATION_FILEDATA" ("TASK_ID" ASC, "ROW_DATA_NUMBER" ASC);

-- ----------------------------
-- Primary Key structure for table t_ods_valuation_sheet_style
-- ----------------------------
ALTER TABLE "T_ODS_VALUATION_SHEET_STYLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_ods_valuation_sheet_style
-- ----------------------------
CREATE UNIQUE INDEX "UK_ODS_SHEET_STYLE_FILE_SHEET_SCOPE"
  ON "T_ODS_VALUATION_SHEET_STYLE" ("FILE_ID" ASC, "SHEET_NAME" ASC, "STYLE_SCOPE" ASC);
CREATE INDEX "IDX_ODS_SHEET_STYLE_TASK_ID"
  ON "T_ODS_VALUATION_SHEET_STYLE" ("TASK_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_parse_queue
-- ----------------------------
ALTER TABLE "T_PARSE_QUEUE" ADD PRIMARY KEY ("QUEUE_ID");

-- ----------------------------
-- Indexes structure for table t_parse_queue
-- ----------------------------
CREATE UNIQUE INDEX "UK_PARSE_QUEUE_BUSINESS_KEY"
  ON "T_PARSE_QUEUE" ("BUSINESS_KEY" ASC);
CREATE INDEX "IDX_PARSE_QUEUE_TRANSFER_ID"
  ON "T_PARSE_QUEUE" ("TRANSFER_ID" ASC);
CREATE INDEX "IDX_PARSE_QUEUE_SOURCE_CODE"
  ON "T_PARSE_QUEUE" ("SOURCE_CODE" ASC);
CREATE INDEX "IDX_PARSE_QUEUE_ROUTE_ID"
  ON "T_PARSE_QUEUE" ("ROUTE_ID" ASC);
CREATE INDEX "IDX_PARSE_QUEUE_TAG_CODE"
  ON "T_PARSE_QUEUE" ("TAG_CODE" ASC);
CREATE INDEX "IDX_PARSE_QUEUE_PARSE_STATUS"
  ON "T_PARSE_QUEUE" ("PARSE_STATUS" ASC);

-- ----------------------------
-- Primary Key structure for table t_stg_external_valuation
-- ----------------------------
ALTER TABLE "T_STG_EXTERNAL_VALUATION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_stg_external_valuation
-- ----------------------------
CREATE INDEX "IDX_STG_VAL_FILE_ID"
  ON "T_STG_EXTERNAL_VALUATION" ("FILE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_stg_external_valuation_basic_info
-- ----------------------------
ALTER TABLE "T_STG_EXTERNAL_VALUATION_BASIC_INFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_stg_external_valuation_basic_info
-- ----------------------------
CREATE INDEX "IDX_STG_BASIC_INFO_VID_ORDER"
  ON "T_STG_EXTERNAL_VALUATION_BASIC_INFO" ("VALUATION_ID" ASC, "SORT_ORDER" ASC);

-- ----------------------------
-- Primary Key structure for table t_stg_external_valuation_header
-- ----------------------------
ALTER TABLE "T_STG_EXTERNAL_VALUATION_HEADER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_stg_external_valuation_header
-- ----------------------------
CREATE INDEX "IDX_STG_HEADER_VID_COL"
  ON "T_STG_EXTERNAL_VALUATION_HEADER" ("VALUATION_ID" ASC, "COLUMN_INDEX" ASC);

-- ----------------------------
-- Primary Key structure for table t_stg_external_valuation_metric
-- ----------------------------
ALTER TABLE "T_STG_EXTERNAL_VALUATION_METRIC" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_stg_external_valuation_metric
-- ----------------------------
CREATE INDEX "IDX_STG_METRIC_VID_ROW"
  ON "T_STG_EXTERNAL_VALUATION_METRIC" ("VALUATION_ID" ASC, "ROW_DATA_NUMBER" ASC);

-- ----------------------------
-- Primary Key structure for table t_stg_external_valuation_subject
-- ----------------------------
ALTER TABLE "T_STG_EXTERNAL_VALUATION_SUBJECT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_stg_external_valuation_subject
-- ----------------------------
CREATE INDEX "IDX_STG_SUBJECT_VID_ROW"
  ON "T_STG_EXTERNAL_VALUATION_SUBJECT" ("VALUATION_ID" ASC, "ROW_DATA_NUMBER" ASC);

-- ----------------------------
-- Primary Key structure for table t_subject_match_result
-- ----------------------------
ALTER TABLE "T_SUBJECT_MATCH_RESULT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_subject_match_result
-- ----------------------------
CREATE INDEX "IDX_MATCH_RESULT_FILE_ID"
  ON "T_SUBJECT_MATCH_RESULT" ("FILE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_tr_index
-- ----------------------------
ALTER TABLE "T_TR_INDEX" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_tr_index
-- ----------------------------
CREATE INDEX "IDX_T_TR_INDEX_DATE_ORG_PD"
  ON "T_TR_INDEX" ("BIZ_DATE" ASC, "ORG_CD" ASC, "PD_CD" ASC);

-- ----------------------------
-- Primary Key structure for table t_tr_jjhzgzb
-- ----------------------------
ALTER TABLE "T_TR_JJHZGZB" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_tr_jjhzgzb
-- ----------------------------
CREATE INDEX "IDX_TR_JJHZGZB_ORG"
  ON "T_TR_JJHZGZB" ("ORG_CD" ASC);
CREATE INDEX "IDX_TR_JJHZGZB_SUBJECT"
  ON "T_TR_JJHZGZB" ("SUBJECT_CD" ASC);
CREATE INDEX "IDX_TR_JJHZGZB_BIZ_DATE"
  ON "T_TR_JJHZGZB" ("BIZ_DATE" ASC);
CREATE INDEX "IDX_TR_JJHZGZB_PD"
  ON "T_TR_JJHZGZB" ("PD_CD" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_delivery_record
-- ----------------------------
ALTER TABLE "T_TRANSFER_DELIVERY_RECORD" ADD PRIMARY KEY ("DELIVERY_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_delivery_record
-- ----------------------------
CREATE INDEX "IDX_TRANSFER_DELIVERY_ROUTE_ID"
  ON "T_TRANSFER_DELIVERY_RECORD" ("ROUTE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_mail_info
-- ----------------------------
ALTER TABLE "T_TRANSFER_MAIL_INFO" ADD PRIMARY KEY ("TRANSFER_ID");

-- ----------------------------
-- Primary Key structure for table t_transfer_object
-- ----------------------------
ALTER TABLE "T_TRANSFER_OBJECT" ADD PRIMARY KEY ("TRANSFER_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_object
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_OBJECT_FINGERPRINT"
  ON "T_TRANSFER_OBJECT" ("FINGERPRINT" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_object_tag
-- ----------------------------
ALTER TABLE "T_TRANSFER_OBJECT_TAG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table t_transfer_object_tag
-- ----------------------------
CREATE INDEX "IDX_TRANSFER_OBJECT_TAG_TRANSFER_ID"
  ON "T_TRANSFER_OBJECT_TAG" ("TRANSFER_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_route
-- ----------------------------
ALTER TABLE "T_TRANSFER_ROUTE" ADD PRIMARY KEY ("ROUTE_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_route
-- ----------------------------
CREATE INDEX "IDX_TRANSFER_ROUTE_SOURCE_CODE"
  ON "T_TRANSFER_ROUTE" ("SOURCE_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_rule
-- ----------------------------
ALTER TABLE "T_TRANSFER_RULE" ADD PRIMARY KEY ("RULE_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_rule
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_RULE_CODE"
  ON "T_TRANSFER_RULE" ("RULE_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_run_log
-- ----------------------------
ALTER TABLE "T_TRANSFER_RUN_LOG" ADD PRIMARY KEY ("RUN_LOG_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_run_log
-- ----------------------------
CREATE INDEX "IDX_TRANSFER_RUN_LOG_SOURCE_ID"
  ON "T_TRANSFER_RUN_LOG" ("SOURCE_ID" ASC);
CREATE INDEX "IDX_TRANSFER_RUN_LOG_TRANSFER_ID"
  ON "T_TRANSFER_RUN_LOG" ("TRANSFER_ID" ASC);
CREATE INDEX "IDX_TRANSFER_RUN_LOG_ROUTE_ID"
  ON "T_TRANSFER_RUN_LOG" ("ROUTE_ID" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_source
-- ----------------------------
ALTER TABLE "T_TRANSFER_SOURCE" ADD PRIMARY KEY ("SOURCE_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_source
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_SOURCE_CODE"
  ON "T_TRANSFER_SOURCE" ("SOURCE_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_source_checkpoint
-- ----------------------------
ALTER TABLE "T_TRANSFER_SOURCE_CHECKPOINT" ADD PRIMARY KEY ("CHECKPOINT_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_source_checkpoint
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_SOURCE_CHECKPOINT_SOURCE_KEY"
  ON "T_TRANSFER_SOURCE_CHECKPOINT" ("SOURCE_ID" ASC, "CHECKPOINT_KEY" ASC);
CREATE INDEX "IDX_TRANSFER_SOURCE_CHECKPOINT_SOURCE_ID"
  ON "T_TRANSFER_SOURCE_CHECKPOINT" ("SOURCE_ID" ASC);
CREATE INDEX "IDX_TRANSFER_SOURCE_CHECKPOINT_SOURCE_TYPE"
  ON "T_TRANSFER_SOURCE_CHECKPOINT" ("SOURCE_TYPE" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_source_checkpoint_item
-- ----------------------------
ALTER TABLE "T_TRANSFER_SOURCE_CHECKPOINT_ITEM" ADD PRIMARY KEY ("CHECKPOINT_ITEM_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_source_checkpoint_item
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_SOURCE_CHECKPOINT_ITEM_SOURCE_KEY"
  ON "T_TRANSFER_SOURCE_CHECKPOINT_ITEM" ("SOURCE_ID" ASC, "ITEM_KEY" ASC);
CREATE INDEX "IDX_TRANSFER_SOURCE_CHECKPOINT_ITEM_SOURCE_ID"
  ON "T_TRANSFER_SOURCE_CHECKPOINT_ITEM" ("SOURCE_ID" ASC);
CREATE INDEX "IDX_TRANSFER_SOURCE_CHECKPOINT_ITEM_SOURCE_TYPE"
  ON "T_TRANSFER_SOURCE_CHECKPOINT_ITEM" ("SOURCE_TYPE" ASC);
CREATE INDEX "IDX_TRANSFER_SOURCE_CHECKPOINT_ITEM_PROCESSED_AT"
  ON "T_TRANSFER_SOURCE_CHECKPOINT_ITEM" ("PROCESSED_AT" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_tag
-- ----------------------------
ALTER TABLE "T_TRANSFER_TAG" ADD PRIMARY KEY ("TAG_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_tag
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_TAG_CODE"
  ON "T_TRANSFER_TAG" ("TAG_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_transfer_target
-- ----------------------------
ALTER TABLE "T_TRANSFER_TARGET" ADD PRIMARY KEY ("TARGET_ID");

-- ----------------------------
-- Indexes structure for table t_transfer_target
-- ----------------------------
CREATE UNIQUE INDEX "UK_TRANSFER_TARGET_CODE"
  ON "T_TRANSFER_TARGET" ("TARGET_CODE" ASC);

-- ----------------------------
-- Primary Key structure for table t_valset_file_ingest_log
-- ----------------------------
ALTER TABLE "T_VALSET_FILE_INGEST_LOG" ADD PRIMARY KEY ("INGEST_ID");

-- ----------------------------
-- Indexes structure for table t_valset_file_ingest_log
-- ----------------------------
CREATE INDEX "IDX_VALSET_INGEST_FILE_ID"
  ON "T_VALSET_FILE_INGEST_LOG" ("FILE_ID" ASC);
CREATE INDEX "IDX_VALSET_INGEST_CHANNEL_MSG"
  ON "T_VALSET_FILE_INGEST_LOG" ("SOURCE_CHANNEL" ASC, "CHANNEL_MESSAGE_ID" ASC);
