--liquibase formatted sql

--changeset codex:20260502-01-mysql-transfer-seed dbms:mysql
INSERT INTO t_transfer_target (
    target_id,
    target_code,
    target_name,
    target_type,
    enabled,
    target_path_template,
    connection_config_json,
    target_meta_json,
    created_at,
    updated_at
) VALUES (
    2048378688403161090,
    'yss-filesys',
    'yss文件服务',
    'FILESYS',
    0,
    '/yss/gz/${yyyyMMdd}',
    '{"chunkSize":8388608,"parentId":"283e6c2a0fcf4b1488db5856ad074806","storageSettingId":"9a4350d87d4b4085a5fa1a4e8038e09d"}',
    '{}',
    '2026-04-26 20:28:31',
    '2026-04-28 21:34:39'
) ON DUPLICATE KEY UPDATE
    target_id = VALUES(target_id),
    target_name = VALUES(target_name),
    target_type = VALUES(target_type),
    enabled = VALUES(enabled),
    target_path_template = VALUES(target_path_template),
    connection_config_json = VALUES(connection_config_json),
    target_meta_json = VALUES(target_meta_json),
    created_at = VALUES(created_at),
    updated_at = VALUES(updated_at);

INSERT INTO t_transfer_target (
    target_id,
    target_code,
    target_name,
    target_type,
    enabled,
    target_path_template,
    connection_config_json,
    target_meta_json,
    created_at,
    updated_at
) VALUES (
    2048704109511176193,
    'sftp-local',
    'sftp-local',
    'SFTP',
    1,
    '/upload/${yyyyMMdd}',
    '{"port":2222,"strictHostKeyChecking":false,"connectTimeoutMillis":10000,"channelTimeoutMillis":10000,"remoteDir":"/upload/${yyyyMMdd}","host":"127.0.0.1","username":"foo","password":"ENC:v1:uI5mmRT4M3UkP6tqypkiOlADzdsZ6WjOz/Z0Zjgp0c8="}',
    '{}',
    '2026-04-27 18:01:37',
    '2026-04-27 18:07:37'
) ON DUPLICATE KEY UPDATE
    target_id = VALUES(target_id),
    target_name = VALUES(target_name),
    target_type = VALUES(target_type),
    enabled = VALUES(enabled),
    target_path_template = VALUES(target_path_template),
    connection_config_json = VALUES(connection_config_json),
    target_meta_json = VALUES(target_meta_json),
    created_at = VALUES(created_at),
    updated_at = VALUES(updated_at);

INSERT INTO t_transfer_source (
    source_id,
    source_code,
    source_name,
    source_type,
    enabled,
    poll_cron,
    connection_config_json,
    source_meta_json,
    created_at,
    updated_at,
    ingest_status,
    ingest_started_at,
    ingest_finished_at,
    ingest_trigger_type
) VALUES (
    2047251110490148865,
    'qq-mail',
    'qq邮箱',
    'EMAIL',
    1,
    NULL,
    '{"protocol":"imap","folder":"INBOX","ssl":true,"startTls":true,"limit":20,"host":"imap.qq.com","port":993,"username":"slime365@foxmail.com","password":"ENC:v1:jhmvHvULmMKsyx/s3/M7M1+iB+0/vIL0TZM4vvGpJ3XcDkCWmHFGJ0fAP9w=","mailCondition":{"id":"root","type":"GROUP","logicalOp":"AND","children":[{"id":"ycb_1777030191725_20","type":"LEAF","field":"attachmentFileType","operator":"CONTAINS","value":["xls","xlsx"],"betweenValue1":"","betweenValue2":""},{"id":"ycb_1777030202954_21","type":"LEAF","field":"limit","operator":"<=","value":"100","betweenValue1":"","betweenValue2":""}]},"processedMailIds":["<CAMVmqyuAZ3O+EgPkb=Fth+ipXK-MNxapCyEQa11XHW8WGqF=1Q@mail.gmail.com>","<CAMVmqyu67s=Sn5crVOVawL3yqhF+q0DgdXY8nnA5-+H06tKv2w@mail.gmail.com>","<DE2CA002-C3C4-4F59-AAAA-725957EEEB33@icloud.com>","<7E9D9F29-7B37-4021-B428-97A0F580F0AA@icloud.com>","<E36B2128-3B6F-4D43-B3F7-80BCDD32928F@icloud.com>","<943270B7-F86B-4EC6-9813-0D534B43909D@icloud.com>","<C5D32EAD-72AB-43BD-88BB-F09975597586@icloud.com>","<70E95F1F-FA9F-4763-BFF9-A2DB94B27F76@icloud.com>","<C928CFC8-4801-4048-8926-1F8FD4BC5ED3@icloud.com>","<1056d318b5cb9727966b85d417a331d2@ysstech.com>","<20250221165810.5611296b@smtp.qiye.163.com>","<042D805A-D07C-4283-AEE2-539ACBC63A3F@icloud.com>","<E0C12C62-D3DA-474D-8AA9-FD6FD3AE4A1D@icloud.com>","<8AA881A2-586F-46E4-BD06-B89D8C885E26@icloud.com>","<0BE6351E-F212-44A4-932D-963994D7E529@icloud.com>","<e6b34fbeea59736976b90979490cd1c5@ysstech.com>","<b500e382ff7d00aab6e8f28e768f4318@ysstech.com>","<179E0147-C975-4F8C-9000-453F5F0B87F8@icloud.com>","<19b0d8d2b5e15daaf0d8a1d71b33f7a1@ysstech.com>","<48046daa5c9d159bdea18fe040401a58@ysstech.com>","<e6b2e7ca84ff14e5bbdf865488192629@ysstech.com>","<AB838945-913C-4F6C-8EB0-29094B191D15@icloud.com>","<03dc71307627dd3b7d36f64ddc51c682@ysstech.com>","<c673701989944dc8646bd6cb4dfa82c6@ysstech.com>","<a18dedf6996f9df187c3c9d7bd537a16@ysstech.com>","<db3ed33ba6543e309e6500d4c4a79be7@ysstech.com>"],"mailTimeRangeDays":"0"}',
    '{}',
    '2026-04-23 17:47:55',
    '2026-05-01 21:17:57',
    'IDLE',
    '2026-05-01 21:17:20',
    '2026-05-01 21:17:57',
    'MANUAL'
) ON DUPLICATE KEY UPDATE
    source_id = VALUES(source_id),
    source_name = VALUES(source_name),
    source_type = VALUES(source_type),
    enabled = VALUES(enabled),
    poll_cron = VALUES(poll_cron),
    connection_config_json = VALUES(connection_config_json),
    source_meta_json = VALUES(source_meta_json),
    created_at = VALUES(created_at),
    updated_at = VALUES(updated_at),
    ingest_status = VALUES(ingest_status),
    ingest_started_at = VALUES(ingest_started_at),
    ingest_finished_at = VALUES(ingest_finished_at),
    ingest_trigger_type = VALUES(ingest_trigger_type);

INSERT INTO t_transfer_source (
    source_id,
    source_code,
    source_name,
    source_type,
    enabled,
    poll_cron,
    connection_config_json,
    source_meta_json,
    created_at,
    updated_at,
    ingest_status,
    ingest_started_at,
    ingest_finished_at,
    ingest_trigger_type
) VALUES (
    2048751975289450497,
    'local-dir',
    '本地文件管理',
    'LOCAL_DIR',
    1,
    NULL,
    '{"directory":"/Users/zhudaoming/文件管理/upload","recursive":false,"includeHidden":false,"limit":100,"mailCondition":{"id":"root","type":"GROUP","logicalOp":"AND","children":[]}}',
    '{}',
    '2026-04-27 21:11:50',
    '2026-04-28 21:41:26',
    'IDLE',
    '2026-04-28 21:30:00',
    '2026-04-28 21:30:00',
    'CRON'
) ON DUPLICATE KEY UPDATE
    source_id = VALUES(source_id),
    source_name = VALUES(source_name),
    source_type = VALUES(source_type),
    enabled = VALUES(enabled),
    poll_cron = VALUES(poll_cron),
    connection_config_json = VALUES(connection_config_json),
    source_meta_json = VALUES(source_meta_json),
    created_at = VALUES(created_at),
    updated_at = VALUES(updated_at),
    ingest_status = VALUES(ingest_status),
    ingest_started_at = VALUES(ingest_started_at),
    ingest_finished_at = VALUES(ingest_finished_at),
    ingest_trigger_type = VALUES(ingest_trigger_type);

INSERT INTO t_transfer_source (
    source_id,
    source_code,
    source_name,
    source_type,
    enabled,
    poll_cron,
    connection_config_json,
    source_meta_json,
    created_at,
    updated_at,
    ingest_status,
    ingest_started_at,
    ingest_finished_at,
    ingest_trigger_type
) VALUES (
    2049128417319718913,
    '手动上传文件',
    'HTTP手动上传',
    'HTTP',
    1,
    NULL,
    '{"allowMultipleFiles":true,"limit":100,"mailCondition":{"id":"root","type":"GROUP","logicalOp":"AND","children":[]}}',
    '{}',
    '2026-04-28 22:07:40',
    '2026-05-01 21:15:08',
    'IDLE',
    '2026-05-01 21:15:08',
    '2026-05-01 21:15:08',
    'CRON'
) ON DUPLICATE KEY UPDATE
    source_id = VALUES(source_id),
    source_name = VALUES(source_name),
    source_type = VALUES(source_type),
    enabled = VALUES(enabled),
    poll_cron = VALUES(poll_cron),
    connection_config_json = VALUES(connection_config_json),
    source_meta_json = VALUES(source_meta_json),
    created_at = VALUES(created_at),
    updated_at = VALUES(updated_at),
    ingest_status = VALUES(ingest_status),
    ingest_started_at = VALUES(ingest_started_at),
    ingest_finished_at = VALUES(ingest_finished_at),
    ingest_trigger_type = VALUES(ingest_trigger_type);

INSERT INTO t_transfer_rule (
    rule_id,
    rule_code,
    rule_name,
    rule_version,
    enabled,
    priority,
    match_strategy,
    script_language,
    script_body,
    effective_from,
    effective_to,
    rule_meta_json
) VALUES (
    2047251487037984770,
    'all-file',
    '只收取估值表',
    '1.0.0',
    1,
    10,
    'SCRIPT_RULE',
    'qlexpress4',
    'regexList = [\'.*估值.*\\\\.xlsx?\',\'.*农银.*\\\\.xlsx?\',\'.*基金.*\\\\.xlsx?\']\nreturn matchesAnyRegex(fileName, regexList)',
    NULL,
    NULL,
    '{"targetType":"FILESYS","targetCode":"filesys-archive","targetPath":"/transfer/inbox","retryDelaySeconds":60,"renamePattern":"${fileName}","maxRetryCount":3}'
) ON DUPLICATE KEY UPDATE
    rule_id = VALUES(rule_id),
    rule_name = VALUES(rule_name),
    rule_version = VALUES(rule_version),
    enabled = VALUES(enabled),
    priority = VALUES(priority),
    match_strategy = VALUES(match_strategy),
    script_language = VALUES(script_language),
    script_body = VALUES(script_body),
    effective_from = VALUES(effective_from),
    effective_to = VALUES(effective_to),
    rule_meta_json = VALUES(rule_meta_json);

INSERT INTO t_transfer_rule (
    rule_id,
    rule_code,
    rule_name,
    rule_version,
    enabled,
    priority,
    match_strategy,
    script_language,
    script_body,
    effective_from,
    effective_to,
    rule_meta_json
) VALUES (
    2048752573393006593,
    'datafileall',
    '所有文件类型',
    '1.0.0',
    1,
    10,
    'ALL',
    'qlexpress4',
    '',
    NULL,
    NULL,
    '{"targetType":"FILESYS","targetCode":"filesys-archive","targetPath":"/transfer/inbox","retryDelaySeconds":60}'
) ON DUPLICATE KEY UPDATE
    rule_id = VALUES(rule_id),
    rule_name = VALUES(rule_name),
    rule_version = VALUES(rule_version),
    enabled = VALUES(enabled),
    priority = VALUES(priority),
    match_strategy = VALUES(match_strategy),
    script_language = VALUES(script_language),
    script_body = VALUES(script_body),
    effective_from = VALUES(effective_from),
    effective_to = VALUES(effective_to),
    rule_meta_json = VALUES(rule_meta_json);

INSERT INTO t_transfer_route (
    route_id,
    rule_id,
    target_type,
    target_code,
    enabled,
    target_path,
    rename_pattern,
    route_status,
    route_meta_json,
    source_id,
    source_type,
    source_code,
    poll_cron
) VALUES (
    2047257753529483266,
    2047251487037984770,
    'SFTP',
    'sftp-local',
    1,
    '/upload/${yyyyMMdd}',
    NULL,
    'PENDING',
    '{}',
    2047251110490148865,
    'EMAIL',
    'qq-mail',
    '0 0/15 * * * ? *'
) ON DUPLICATE KEY UPDATE
    rule_id = VALUES(rule_id),
    target_type = VALUES(target_type),
    target_code = VALUES(target_code),
    enabled = VALUES(enabled),
    target_path = VALUES(target_path),
    rename_pattern = VALUES(rename_pattern),
    route_status = VALUES(route_status),
    route_meta_json = VALUES(route_meta_json),
    source_id = VALUES(source_id),
    source_type = VALUES(source_type),
    source_code = VALUES(source_code),
    poll_cron = VALUES(poll_cron);

INSERT INTO t_transfer_route (
    route_id,
    rule_id,
    target_type,
    target_code,
    enabled,
    target_path,
    rename_pattern,
    route_status,
    route_meta_json,
    source_id,
    source_type,
    source_code,
    poll_cron
) VALUES (
    2048752665197932545,
    2048752573393006593,
    'SFTP',
    'sftp-local',
    1,
    '/upload/${yyyyMMdd}',
    NULL,
    'PENDING',
    '{}',
    2049128417319718913,
    'HTTP',
    '手动上传文件',
    '0 0/15 * * * ? *'
) ON DUPLICATE KEY UPDATE
    rule_id = VALUES(rule_id),
    target_type = VALUES(target_type),
    target_code = VALUES(target_code),
    enabled = VALUES(enabled),
    target_path = VALUES(target_path),
    rename_pattern = VALUES(rename_pattern),
    route_status = VALUES(route_status),
    route_meta_json = VALUES(route_meta_json),
    source_id = VALUES(source_id),
    source_type = VALUES(source_type),
    source_code = VALUES(source_code),
    poll_cron = VALUES(poll_cron);

--changeset codex:20260502-01-postgres-transfer-seed dbms:postgresql
INSERT INTO t_transfer_target (
    target_id,
    target_code,
    target_name,
    target_type,
    enabled,
    target_path_template,
    connection_config_json,
    target_meta_json,
    created_at,
    updated_at
) VALUES (
    2048378688403161090,
    'yss-filesys',
    'yss文件服务',
    'FILESYS',
    FALSE,
    '/yss/gz/${yyyyMMdd}',
    '{"chunkSize":8388608,"parentId":"283e6c2a0fcf4b1488db5856ad074806","storageSettingId":"9a4350d87d4b4085a5fa1a4e8038e09d"}',
    '{}',
    TIMESTAMP '2026-04-26 20:28:31',
    TIMESTAMP '2026-04-28 21:34:39'
) ON CONFLICT (target_code) DO UPDATE SET
    target_id = EXCLUDED.target_id,
    target_name = EXCLUDED.target_name,
    target_type = EXCLUDED.target_type,
    enabled = EXCLUDED.enabled,
    target_path_template = EXCLUDED.target_path_template,
    connection_config_json = EXCLUDED.connection_config_json,
    target_meta_json = EXCLUDED.target_meta_json,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at;

INSERT INTO t_transfer_target (
    target_id,
    target_code,
    target_name,
    target_type,
    enabled,
    target_path_template,
    connection_config_json,
    target_meta_json,
    created_at,
    updated_at
) VALUES (
    2048704109511176193,
    'sftp-local',
    'sftp-local',
    'SFTP',
    TRUE,
    '/upload/${yyyyMMdd}',
    '{"port":2222,"strictHostKeyChecking":false,"connectTimeoutMillis":10000,"channelTimeoutMillis":10000,"remoteDir":"/upload/${yyyyMMdd}","host":"127.0.0.1","username":"foo","password":"ENC:v1:uI5mmRT4M3UkP6tqypkiOlADzdsZ6WjOz/Z0Zjgp0c8="}',
    '{}',
    TIMESTAMP '2026-04-27 18:01:37',
    TIMESTAMP '2026-04-27 18:07:37'
) ON CONFLICT (target_code) DO UPDATE SET
    target_id = EXCLUDED.target_id,
    target_name = EXCLUDED.target_name,
    target_type = EXCLUDED.target_type,
    enabled = EXCLUDED.enabled,
    target_path_template = EXCLUDED.target_path_template,
    connection_config_json = EXCLUDED.connection_config_json,
    target_meta_json = EXCLUDED.target_meta_json,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at;

INSERT INTO t_transfer_source (
    source_id,
    source_code,
    source_name,
    source_type,
    enabled,
    poll_cron,
    connection_config_json,
    source_meta_json,
    created_at,
    updated_at,
    ingest_status,
    ingest_started_at,
    ingest_finished_at,
    ingest_trigger_type
) VALUES (
    2047251110490148865,
    'qq-mail',
    'qq邮箱',
    'EMAIL',
    TRUE,
    NULL,
    '{"protocol":"imap","folder":"INBOX","ssl":true,"startTls":true,"limit":20,"host":"imap.qq.com","port":993,"username":"slime365@foxmail.com","password":"ENC:v1:jhmvHvULmMKsyx/s3/M7M1+iB+0/vIL0TZM4vvGpJ3XcDkCWmHFGJ0fAP9w=","mailCondition":{"id":"root","type":"GROUP","logicalOp":"AND","children":[{"id":"ycb_1777030191725_20","type":"LEAF","field":"attachmentFileType","operator":"CONTAINS","value":["xls","xlsx"],"betweenValue1":"","betweenValue2":""},{"id":"ycb_1777030202954_21","type":"LEAF","field":"limit","operator":"<=","value":"100","betweenValue1":"","betweenValue2":""}]},"processedMailIds":["<CAMVmqyuAZ3O+EgPkb=Fth+ipXK-MNxapCyEQa11XHW8WGqF=1Q@mail.gmail.com>","<CAMVmqyu67s=Sn5crVOVawL3yqhF+q0DgdXY8nnA5-+H06tKv2w@mail.gmail.com>","<DE2CA002-C3C4-4F59-AAAA-725957EEEB33@icloud.com>","<7E9D9F29-7B37-4021-B428-97A0F580F0AA@icloud.com>","<E36B2128-3B6F-4D43-B3F7-80BCDD32928F@icloud.com>","<943270B7-F86B-4EC6-9813-0D534B43909D@icloud.com>","<C5D32EAD-72AB-43BD-88BB-F09975597586@icloud.com>","<70E95F1F-FA9F-4763-BFF9-A2DB94B27F76@icloud.com>","<C928CFC8-4801-4048-8926-1F8FD4BC5ED3@icloud.com>","<1056d318b5cb9727966b85d417a331d2@ysstech.com>","<20250221165810.5611296b@smtp.qiye.163.com>","<042D805A-D07C-4283-AEE2-539ACBC63A3F@icloud.com>","<E0C12C62-D3DA-474D-8AA9-FD6FD3AE4A1D@icloud.com>","<8AA881A2-586F-46E4-BD06-B89D8C885E26@icloud.com>","<0BE6351E-F212-44A4-932D-963994D7E529@icloud.com>","<e6b34fbeea59736976b90979490cd1c5@ysstech.com>","<b500e382ff7d00aab6e8f28e768f4318@ysstech.com>","<179E0147-C975-4F8C-9000-453F5F0B87F8@icloud.com>","<19b0d8d2b5e15daaf0d8a1d71b33f7a1@ysstech.com>","<48046daa5c9d159bdea18fe040401a58@ysstech.com>","<e6b2e7ca84ff14e5bbdf865488192629@ysstech.com>","<AB838945-913C-4F6C-8EB0-29094B191D15@icloud.com>","<03dc71307627dd3b7d36f64ddc51c682@ysstech.com>","<c673701989944dc8646bd6cb4dfa82c6@ysstech.com>","<a18dedf6996f9df187c3c9d7bd537a16@ysstech.com>","<db3ed33ba6543e309e6500d4c4a79be7@ysstech.com>"],"mailTimeRangeDays":"0"}',
    '{}',
    TIMESTAMP '2026-04-23 17:47:55',
    TIMESTAMP '2026-05-01 21:17:57',
    'IDLE',
    TIMESTAMP '2026-05-01 21:17:20',
    TIMESTAMP '2026-05-01 21:17:57',
    'MANUAL'
) ON CONFLICT (source_code) DO UPDATE SET
    source_id = EXCLUDED.source_id,
    source_name = EXCLUDED.source_name,
    source_type = EXCLUDED.source_type,
    enabled = EXCLUDED.enabled,
    poll_cron = EXCLUDED.poll_cron,
    connection_config_json = EXCLUDED.connection_config_json,
    source_meta_json = EXCLUDED.source_meta_json,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    ingest_status = EXCLUDED.ingest_status,
    ingest_started_at = EXCLUDED.ingest_started_at,
    ingest_finished_at = EXCLUDED.ingest_finished_at,
    ingest_trigger_type = EXCLUDED.ingest_trigger_type;

INSERT INTO t_transfer_source (
    source_id,
    source_code,
    source_name,
    source_type,
    enabled,
    poll_cron,
    connection_config_json,
    source_meta_json,
    created_at,
    updated_at,
    ingest_status,
    ingest_started_at,
    ingest_finished_at,
    ingest_trigger_type
) VALUES (
    2048751975289450497,
    'local-dir',
    '本地文件管理',
    'LOCAL_DIR',
    TRUE,
    NULL,
    '{"directory":"/Users/zhudaoming/文件管理/upload","recursive":false,"includeHidden":false,"limit":100,"mailCondition":{"id":"root","type":"GROUP","logicalOp":"AND","children":[]}}',
    '{}',
    TIMESTAMP '2026-04-27 21:11:50',
    TIMESTAMP '2026-04-28 21:41:26',
    'IDLE',
    TIMESTAMP '2026-04-28 21:30:00',
    TIMESTAMP '2026-04-28 21:30:00',
    'CRON'
) ON CONFLICT (source_code) DO UPDATE SET
    source_id = EXCLUDED.source_id,
    source_name = EXCLUDED.source_name,
    source_type = EXCLUDED.source_type,
    enabled = EXCLUDED.enabled,
    poll_cron = EXCLUDED.poll_cron,
    connection_config_json = EXCLUDED.connection_config_json,
    source_meta_json = EXCLUDED.source_meta_json,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    ingest_status = EXCLUDED.ingest_status,
    ingest_started_at = EXCLUDED.ingest_started_at,
    ingest_finished_at = EXCLUDED.ingest_finished_at,
    ingest_trigger_type = EXCLUDED.ingest_trigger_type;

INSERT INTO t_transfer_source (
    source_id,
    source_code,
    source_name,
    source_type,
    enabled,
    poll_cron,
    connection_config_json,
    source_meta_json,
    created_at,
    updated_at,
    ingest_status,
    ingest_started_at,
    ingest_finished_at,
    ingest_trigger_type
) VALUES (
    2049128417319718913,
    '手动上传文件',
    'HTTP手动上传',
    'HTTP',
    TRUE,
    NULL,
    '{"allowMultipleFiles":true,"limit":100,"mailCondition":{"id":"root","type":"GROUP","logicalOp":"AND","children":[]}}',
    '{}',
    TIMESTAMP '2026-04-28 22:07:40',
    TIMESTAMP '2026-05-01 21:15:08',
    'IDLE',
    TIMESTAMP '2026-05-01 21:15:08',
    TIMESTAMP '2026-05-01 21:15:08',
    'CRON'
) ON CONFLICT (source_code) DO UPDATE SET
    source_id = EXCLUDED.source_id,
    source_name = EXCLUDED.source_name,
    source_type = EXCLUDED.source_type,
    enabled = EXCLUDED.enabled,
    poll_cron = EXCLUDED.poll_cron,
    connection_config_json = EXCLUDED.connection_config_json,
    source_meta_json = EXCLUDED.source_meta_json,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    ingest_status = EXCLUDED.ingest_status,
    ingest_started_at = EXCLUDED.ingest_started_at,
    ingest_finished_at = EXCLUDED.ingest_finished_at,
    ingest_trigger_type = EXCLUDED.ingest_trigger_type;

INSERT INTO t_transfer_rule (
    rule_id,
    rule_code,
    rule_name,
    rule_version,
    enabled,
    priority,
    match_strategy,
    script_language,
    script_body,
    effective_from,
    effective_to,
    rule_meta_json
) VALUES (
    2047251487037984770,
    'all-file',
    '只收取估值表',
    '1.0.0',
    TRUE,
    10,
    'SCRIPT_RULE',
    'qlexpress4',
    'regexList = [''.*估值.*\\.xlsx?'',''.*农银.*\\.xlsx?'',''.*基金.*\\.xlsx?'']\nreturn matchesAnyRegex(fileName, regexList)',
    NULL,
    NULL,
    '{"targetType":"FILESYS","targetCode":"filesys-archive","targetPath":"/transfer/inbox","retryDelaySeconds":60,"renamePattern":"${fileName}","maxRetryCount":3}'
) ON CONFLICT (rule_code) DO UPDATE SET
    rule_id = EXCLUDED.rule_id,
    rule_name = EXCLUDED.rule_name,
    rule_version = EXCLUDED.rule_version,
    enabled = EXCLUDED.enabled,
    priority = EXCLUDED.priority,
    match_strategy = EXCLUDED.match_strategy,
    script_language = EXCLUDED.script_language,
    script_body = EXCLUDED.script_body,
    effective_from = EXCLUDED.effective_from,
    effective_to = EXCLUDED.effective_to,
    rule_meta_json = EXCLUDED.rule_meta_json;

INSERT INTO t_transfer_rule (
    rule_id,
    rule_code,
    rule_name,
    rule_version,
    enabled,
    priority,
    match_strategy,
    script_language,
    script_body,
    effective_from,
    effective_to,
    rule_meta_json
) VALUES (
    2048752573393006593,
    'datafileall',
    '所有文件类型',
    '1.0.0',
    TRUE,
    10,
    'ALL',
    'qlexpress4',
    '',
    NULL,
    NULL,
    '{"targetType":"FILESYS","targetCode":"filesys-archive","targetPath":"/transfer/inbox","retryDelaySeconds":60}'
) ON CONFLICT (rule_code) DO UPDATE SET
    rule_id = EXCLUDED.rule_id,
    rule_name = EXCLUDED.rule_name,
    rule_version = EXCLUDED.rule_version,
    enabled = EXCLUDED.enabled,
    priority = EXCLUDED.priority,
    match_strategy = EXCLUDED.match_strategy,
    script_language = EXCLUDED.script_language,
    script_body = EXCLUDED.script_body,
    effective_from = EXCLUDED.effective_from,
    effective_to = EXCLUDED.effective_to,
    rule_meta_json = EXCLUDED.rule_meta_json;

INSERT INTO t_transfer_route (
    route_id,
    rule_id,
    target_type,
    target_code,
    enabled,
    target_path,
    rename_pattern,
    route_status,
    route_meta_json,
    poll_cron
) VALUES (
    2047257753529483266,
    2047251487037984770,
    'SFTP',
    'sftp-local',
    TRUE,
    '/upload/${yyyyMMdd}',
    NULL,
    'PENDING',
    '{}',
    '0 0/15 * * * ? *'
) ON CONFLICT (route_id) DO UPDATE SET
    rule_id = EXCLUDED.rule_id,
    target_type = EXCLUDED.target_type,
    target_code = EXCLUDED.target_code,
    enabled = EXCLUDED.enabled,
    target_path = EXCLUDED.target_path,
    rename_pattern = EXCLUDED.rename_pattern,
    route_status = EXCLUDED.route_status,
    route_meta_json = EXCLUDED.route_meta_json,
    poll_cron = EXCLUDED.poll_cron;

INSERT INTO t_transfer_route (
    route_id,
    rule_id,
    target_type,
    target_code,
    enabled,
    target_path,
    rename_pattern,
    route_status,
    route_meta_json,
    poll_cron
) VALUES (
    2048752665197932545,
    2048752573393006593,
    'SFTP',
    'sftp-local',
    TRUE,
    '/upload/${yyyyMMdd}',
    NULL,
    'PENDING',
    '{}',
    '0 0/15 * * * ? *'
) ON CONFLICT (route_id) DO UPDATE SET
    rule_id = EXCLUDED.rule_id,
    target_type = EXCLUDED.target_type,
    target_code = EXCLUDED.target_code,
    enabled = EXCLUDED.enabled,
    target_path = EXCLUDED.target_path,
    rename_pattern = EXCLUDED.rename_pattern,
    route_status = EXCLUDED.route_status,
    route_meta_json = EXCLUDED.route_meta_json,
    poll_cron = EXCLUDED.poll_cron;
