--liquibase formatted sql

--changeset codex:20260415-05-mysql-legacy-source dbms:mysql
CREATE TABLE tr_fm_jjhzgzb (
    id BIGINT PRIMARY KEY,
    org_cd VARCHAR(30),
    pd_cd VARCHAR(30),
    biz_date VARCHAR(8),
    subject_cd VARCHAR(100),
    subject_nm VARCHAR(300),
    pa_subject_cd VARCHAR(100),
    pa_subject_nm VARCHAR(300),
    n_hldamt DECIMAL(26, 4),
    n_hldcst DECIMAL(26, 4),
    n_hldcst_locl DECIMAL(26, 4),
    n_hldmkv DECIMAL(26, 4),
    n_hldmkv_locl DECIMAL(26, 4),
    n_hldvva DECIMAL(26, 4),
    n_hldvva_l DECIMAL(26, 4),
    ccy_cd VARCHAR(3),
    n_valrate DECIMAL(26, 4),
    n_price_cost DECIMAL(26, 4),
    n_valprice DECIMAL(26, 4),
    n_cb_jz_bl DECIMAL(26, 4),
    n_sz_jz_bl DECIMAL(26, 4),
    n_zc_bl DECIMAL(26, 8),
    susp_info VARCHAR(300),
    valuat_equity VARCHAR(30),
    fin_attr_id_d VARCHAR(30),
    fin_mkt_cd VARCHAR(30),
    time_stamp DATETIME,
    cons_float_tp_cd VARCHAR(30),
    source_tp VARCHAR(30),
    source_sign VARCHAR(300),
    sn SMALLINT,
    data_dt VARCHAR(8),
    is_audt TINYINT(1),
    audt_id VARCHAR(30),
    isin_cd VARCHAR(30)
);

CREATE TABLE tr_spv_jjhzgzb (
    id BIGINT PRIMARY KEY,
    org_cd VARCHAR(30),
    pd_cd VARCHAR(30),
    biz_date VARCHAR(8),
    subject_cd VARCHAR(100),
    subject_nm VARCHAR(300),
    pa_subject_cd VARCHAR(100),
    pa_subject_nm VARCHAR(300),
    n_hldamt DECIMAL(26, 4),
    n_hldcst DECIMAL(26, 4),
    n_hldcst_locl DECIMAL(26, 4),
    n_hldmkv DECIMAL(26, 4),
    n_hldmkv_locl DECIMAL(26, 4),
    n_hldvva DECIMAL(26, 4),
    n_hldvva_l DECIMAL(26, 4),
    ccy_cd VARCHAR(3),
    n_valrate DECIMAL(26, 4),
    n_price_cost DECIMAL(26, 4),
    n_valprice DECIMAL(26, 4),
    n_cb_jz_bl DECIMAL(26, 4),
    n_sz_jz_bl DECIMAL(26, 4),
    n_zc_bl DECIMAL(26, 8),
    susp_info VARCHAR(300),
    valuat_equity VARCHAR(30),
    fin_attr_id_d VARCHAR(30),
    fin_mkt_cd VARCHAR(30),
    time_stamp DATETIME,
    cons_float_tp_cd VARCHAR(30),
    source_tp VARCHAR(30),
    source_sign VARCHAR(300),
    sn SMALLINT,
    data_dt VARCHAR(8),
    isin_cd VARCHAR(30)
);

--changeset codex:20260415-05-postgres-legacy-source dbms:postgresql
CREATE TABLE tr_fm_jjhzgzb (
    id BIGINT PRIMARY KEY,
    org_cd VARCHAR(30),
    pd_cd VARCHAR(30),
    biz_date VARCHAR(8),
    subject_cd VARCHAR(100),
    subject_nm VARCHAR(300),
    pa_subject_cd VARCHAR(100),
    pa_subject_nm VARCHAR(300),
    n_hldamt NUMERIC(26, 4),
    n_hldcst NUMERIC(26, 4),
    n_hldcst_locl NUMERIC(26, 4),
    n_hldmkv NUMERIC(26, 4),
    n_hldmkv_locl NUMERIC(26, 4),
    n_hldvva NUMERIC(26, 4),
    n_hldvva_l NUMERIC(26, 4),
    ccy_cd VARCHAR(3),
    n_valrate NUMERIC(26, 4),
    n_price_cost NUMERIC(26, 4),
    n_valprice NUMERIC(26, 4),
    n_cb_jz_bl NUMERIC(26, 4),
    n_sz_jz_bl NUMERIC(26, 4),
    n_zc_bl NUMERIC(26, 8),
    susp_info VARCHAR(300),
    valuat_equity VARCHAR(30),
    fin_attr_id_d VARCHAR(30),
    fin_mkt_cd VARCHAR(30),
    time_stamp TIMESTAMP,
    cons_float_tp_cd VARCHAR(30),
    source_tp VARCHAR(30),
    source_sign VARCHAR(300),
    sn SMALLINT,
    data_dt VARCHAR(8),
    is_audt BOOLEAN,
    audt_id VARCHAR(30),
    isin_cd VARCHAR(30)
);

CREATE TABLE tr_spv_jjhzgzb (
    id BIGINT PRIMARY KEY,
    org_cd VARCHAR(30),
    pd_cd VARCHAR(30),
    biz_date VARCHAR(8),
    subject_cd VARCHAR(100),
    subject_nm VARCHAR(300),
    pa_subject_cd VARCHAR(100),
    pa_subject_nm VARCHAR(300),
    n_hldamt NUMERIC(26, 4),
    n_hldcst NUMERIC(26, 4),
    n_hldcst_locl NUMERIC(26, 4),
    n_hldmkv NUMERIC(26, 4),
    n_hldmkv_locl NUMERIC(26, 4),
    n_hldvva NUMERIC(26, 4),
    n_hldvva_l NUMERIC(26, 4),
    ccy_cd VARCHAR(3),
    n_valrate NUMERIC(26, 4),
    n_price_cost NUMERIC(26, 4),
    n_valprice NUMERIC(26, 4),
    n_cb_jz_bl NUMERIC(26, 4),
    n_sz_jz_bl NUMERIC(26, 4),
    n_zc_bl NUMERIC(26, 8),
    susp_info VARCHAR(300),
    valuat_equity VARCHAR(30),
    fin_attr_id_d VARCHAR(30),
    fin_mkt_cd VARCHAR(30),
    time_stamp TIMESTAMP,
    cons_float_tp_cd VARCHAR(30),
    source_tp VARCHAR(30),
    source_sign VARCHAR(300),
    sn SMALLINT,
    data_dt VARCHAR(8),
    isin_cd VARCHAR(30)
);

--changeset codex:20260415-05-oracle-legacy-source dbms:oracle
CREATE TABLE tr_fm_jjhzgzb (
    id NUMBER(19) PRIMARY KEY,
    org_cd VARCHAR2(30 CHAR),
    pd_cd VARCHAR2(30 CHAR),
    biz_date VARCHAR2(8 CHAR),
    subject_cd VARCHAR2(100 CHAR),
    subject_nm VARCHAR2(300 CHAR),
    pa_subject_cd VARCHAR2(100 CHAR),
    pa_subject_nm VARCHAR2(300 CHAR),
    n_hldamt NUMBER(26, 4),
    n_hldcst NUMBER(26, 4),
    n_hldcst_locl NUMBER(26, 4),
    n_hldmkv NUMBER(26, 4),
    n_hldmkv_locl NUMBER(26, 4),
    n_hldvva NUMBER(26, 4),
    n_hldvva_l NUMBER(26, 4),
    ccy_cd VARCHAR2(3 CHAR),
    n_valrate NUMBER(26, 4),
    n_price_cost NUMBER(26, 4),
    n_valprice NUMBER(26, 4),
    n_cb_jz_bl NUMBER(26, 4),
    n_sz_jz_bl NUMBER(26, 4),
    n_zc_bl NUMBER(26, 8),
    susp_info VARCHAR2(300 CHAR),
    valuat_equity VARCHAR2(30 CHAR),
    fin_attr_id_d VARCHAR2(30 CHAR),
    fin_mkt_cd VARCHAR2(30 CHAR),
    time_stamp TIMESTAMP,
    cons_float_tp_cd VARCHAR2(30 CHAR),
    source_tp VARCHAR2(30 CHAR),
    source_sign VARCHAR2(300 CHAR),
    sn NUMBER(5),
    data_dt VARCHAR2(8 CHAR),
    is_audt NUMBER(1),
    audt_id VARCHAR2(30 CHAR),
    isin_cd VARCHAR2(30 CHAR)
);

CREATE TABLE tr_spv_jjhzgzb (
    id NUMBER(19) PRIMARY KEY,
    org_cd VARCHAR2(30 CHAR),
    pd_cd VARCHAR2(30 CHAR),
    biz_date VARCHAR2(8 CHAR),
    subject_cd VARCHAR2(100 CHAR),
    subject_nm VARCHAR2(300 CHAR),
    pa_subject_cd VARCHAR2(100 CHAR),
    pa_subject_nm VARCHAR2(300 CHAR),
    n_hldamt NUMBER(26, 4),
    n_hldcst NUMBER(26, 4),
    n_hldcst_locl NUMBER(26, 4),
    n_hldmkv NUMBER(26, 4),
    n_hldmkv_locl NUMBER(26, 4),
    n_hldvva NUMBER(26, 4),
    n_hldvva_l NUMBER(26, 4),
    ccy_cd VARCHAR2(3 CHAR),
    n_valrate NUMBER(26, 4),
    n_price_cost NUMBER(26, 4),
    n_valprice NUMBER(26, 4),
    n_cb_jz_bl NUMBER(26, 4),
    n_sz_jz_bl NUMBER(26, 4),
    n_zc_bl NUMBER(26, 8),
    susp_info VARCHAR2(300 CHAR),
    valuat_equity VARCHAR2(30 CHAR),
    fin_attr_id_d VARCHAR2(30 CHAR),
    fin_mkt_cd VARCHAR2(30 CHAR),
    time_stamp TIMESTAMP,
    cons_float_tp_cd VARCHAR2(30 CHAR),
    source_tp VARCHAR2(30 CHAR),
    source_sign VARCHAR2(300 CHAR),
    sn NUMBER(5),
    data_dt VARCHAR2(8 CHAR),
    isin_cd VARCHAR2(30 CHAR)
);
