package com.yss.valset.transfer.application.port;

import com.yss.valset.transfer.domain.model.TransferDeliveryRecord;
import com.yss.valset.transfer.domain.model.TransferObject;

/**
 * 投递完成后生成待解析任务的用例。
 */
public interface TransferParseQueueProvisionUseCase {

    void ensureAutoGenerated(TransferObject transferObject, TransferDeliveryRecord deliveryRecord);
}
