package com.yss.valset.application.event.lifecycle;

/**
 * 解析生命周期阶段。
 */
public enum ParseLifecycleStage {
    CYCLE_STARTED,
    CYCLE_FINISHED,
    BATCH_STARTED,
    BATCH_EMPTY,
    BATCH_FINISHED,
    QUEUE_DISCOVERED,
    QUEUE_GENERATED,
    QUEUE_BACKFILLED,
    QUEUE_REUSED,
    QUEUE_UPDATED,
    QUEUE_RETRIED,
    QUEUE_SUBSCRIBE_ATTEMPTED,
    QUEUE_SUBSCRIBED,
    QUEUE_SUBSCRIBE_CONFLICT,
    QUEUE_SUBSCRIBE_SKIPPED,
    QUEUE_FILE_INFO_REPAIR_STARTED,
    QUEUE_FILE_INFO_REPAIR_COMPLETED,
    QUEUE_FILE_INFO_REPAIR_FAILED,
    TASK_REQUEST_BUILT,
    TASK_CREATED,
    TASK_REUSED,
    TASK_DISPATCHED,
    TASK_EXECUTION_STARTED,
    TASK_RAW_PARSED,
    TASK_STANDARDIZED,
    TASK_PERSISTED,
    TASK_SUCCEEDED,
    TASK_FAILED,
    QUEUE_COMPLETED,
    QUEUE_FAILED,
    QUEUE_SKIPPED
}
